### ISSUE TITLE
add download speed to display

### ISSUE THREAD

**Issue by OneCDOnly** [OneCDOnly/sherpa#1]
Not sure if this can be done, but should be investigated anyway. Even if the speed isn't 'live', let's record it in the debug log.

**Comment by teracow** [comment]
opkg has no progress display, so here's a rather involved workaround.

- Monitor the opkg cache directory. This is empty before beginning IPKG download and will fill-up as each package downloads.

- To show how much progress has been made (bytes downloaded/bytes total) or a percentage complete, need to know total download size for all required IPKGs.

- [ ] create list of requested IPKGs,
- [ ] get all dependant IPKGs,
- [ ] remove duplicates,
- [ ] remove IPKGs already installed,
- [ ] get total size of IPKGs that actually need to be downloaded. 
- [ ] spawn directory size watcher that, once per second, sends dir size vs total size to stdout and to a temp file. If temp file is removed, spawned process dies. 
- [ ] launch opkg install with IPKGs requiring download.
- [ ] once download is complete, remove temp file to kill display process.

This is not easy to do. ;)

**Comment by OneCDOnly** [comment]
opkg has no progress display, so here's a rather involved workaround.

- Monitor the opkg cache directory. This is empty before beginning IPKG download and will fill-up as each package downloads.

- To show how much progress has been made (bytes downloaded/bytes total) or a percentage complete, need to know total download size for all required IPKGs.

- [x] create list of requested IPKGs,
- [x] add all dependant IPKGs to list,
- [x] remove duplicates from list,
- [x] remove IPKGs already installed from list,
- [x] get total size of IPKGs that actually need to be downloaded. 
- [ ] spawn directory size watcher that, once per second, sends dir size vs total size to stdout and to a temp file. If temp file is removed, spawned process dies. 
- [ ] launch opkg install with IPKGs requiring download.
- [ ] once download is complete, remove temp file to kill display process.

This is not easy to do. ;)

**Comment by OneCDOnly** [comment]
Fixed in https://github.com/OneCDOnly/sherpa/commit/250e065a109ea48bd2677b3c277292ccf26050a3
