### ISSUE TITLE
SickRage Script

### ISSUE THREAD

**Issue by ouija** [OneCDOnly/sherpa#10]
Hey,

Latest version of SickRage seems to have renamed the init script from SickBeard.py to SiCKRAGE.py and launching the package now throws the error:

`/opt/bin/python2.7: can't open file 'SickBeard.py': [Errno 2] No such file or directory`

Updating the local TARGET_SCRIPT within ./sickrage.sh doesn't seem to resolve the issue; SickRage fails to start.

**Comment by OneCDOnly** [comment]
Hi, yes I've just seen that SickRage now directs to @echel0n's SiCKRAGE - not something I wanted, so I've had to remove references to SickRage earlier than I'd like. 

More to come...

**Comment by echel0n** [comment]
I'm this is echel0n

**Comment by OneCDOnly** [comment]
> I'm this is echel0n

My condolences. Take your drug-addled brain elsewhere.

**Comment by OneCDOnly** [comment]
@ouija should be good to go now. Please download and run the latest sherpa, and install SickChill. It will replace your SickRage installation, and _should_ transfer over all settings.

**Comment by ouija** [comment]
It installed and runs, but did not replace the existing SickRage install or transfer over any of the settings.

**Comment by OneCDOnly** [comment]
Good work. Yes, it ignores QPKGs that are disabled in the App Center. This is so admins can try out other sherpa packages without losing their existing ones.
