### ISSUE TITLE
SABnzbd: error message when installing via ssh

### ISSUE THREAD

**Issue by Kampek01** [OneCDOnly/sherpa#103]
I am getting the error below when trying to install sabnzb on my qnap nas. Who can help me

[~] # cd /share/Public
[/share/Public] # curl -skLO https://git.io/sherpa.sh && chmod +x sherpa.sh
[/share/Public] # ./sherpa.sh SABnzbd
sherpa.sh (200824f)

[ done ] downloaded QPKG (SABnzbd_200824c.qpkg)            
[ done ] updated 'Entware' package list            
[ done ] no IPKGs are required                
[ fail ] A required NAS system file is missing (/opt/bin/pip3) 
* Ugh! The usual fix for this is to let sherpa reinstall 'Entware' at least once.
        /share/__sherpa-main__.sh ew
If it happens again after reinstalling 'Entware', please create a new issue for this on GitHub.
[ fail ] 'SABnzbd' install failed! [0]        

* Please consider creating a new issue for this on GitHub:
        https://github.com/OneCDOnly/sherpa/issues

* Alternatively, post on the QNAP NAS Community Forum:
        https://forum.qnap.com/viewtopic.php?f=320&t=132373

* Remember to include a copy of your sherpa log for analysis.

- View the sherpa log:
        ./sherpa.sh --log

- Upload the sherpa log to a public pastebin (https://termbin.com):
        ./sherpa.sh --paste

[/share/Public] #

**Comment by OneCDOnly** [comment]
Hi and thanks for reporting this. 

Can you please post your `sherpa.debug.log` so I can see where the problem is occurring?

**Comment by OneCDOnly** [comment]
Hi @Kampek01 any progress with this issue?

**Comment by Kampek01** [comment]
Hi Knot,

I found the problem. I first removed all old apps and then installed it all over again with ssh sherpa. All apps have been upgraded due to the new installation. Now it works great again.

Thanks for the support
