### ISSUE TITLE
Fail in sabnzbd install due to -> Download & install 'Python 3' modules failed ! 

### ISSUE THREAD

**Issue by pippotaz** [OneCDOnly/sherpa#108]
[/share/Public] # ./sherpa.sh SABnzbd
sherpa.sh (200825h)

[ done ] downloaded QPKG (Par2_0.8.1.0_x86_64.qpkg)            
[ done ] downloaded QPKG (SABnzbd_200825b.qpkg)            
[ done ] installed QPKG (Par2_0.8.1.0_x86_64.qpkg)                                    
[ done ] updated 'Entware' package list            
[ done ] 42 IPKGs (38MB) to be downloaded     
[ done ] downloaded & installed 42 IPKGs                        
[ fail ] Download & install 'Python 3' modules failed ! result: [1] 
[ fail ] 'SABnzbd' install failed! [0]   

Log here:   https://l.termbin.com/3ymf

**Comment by apache6131** [comment]
I am getting the same issues.
`[/share/Public] # ./sherpa.sh SABnzbd
sherpa.sh (200826)

[ done ] downloaded QPKG (SABnzbd_200826.qpkg)
[ done ] 'Entware' package list is up-to-date
[ done ] no IPKGs are required
ln: /opt/bin/python: File exists
[ fail ] Download & install 'Python 3' modules failed ! result: [1]
[ fail ] 'SABnzbd' install failed! [0]
`
Sherpa log here:  [https://l.termbin.com/kyyd](url)

**Comment by OneCDOnly** [comment]
@pippotaz & @apache6131  can you both please reinstall Entware?
```
./sherpa.sh ew
```

**Comment by pippotaz** [comment]
Entware reinstall fixed it for me but even after a complete nas reboot I can't access Sab trough port 8081 any other port i should try ?

https://l.termbin.com/9w3n

**Comment by OneCDOnly** [comment]
> Entware reinstall fixed it for me but even after a complete nas reboot I can't access Sab trough port 8081 any other port i should try ?

Your log looks fine, so everything should be working now. 

Can you please check the SABnzbd status via the service script? 
```
/etc/init.d/sabznbd3.sh status
```
This will reveal the port(s) SABnzbd is listening on, and will also update App Center with those ports.

**Comment by pippotaz** [comment]
Yep that did it, went to port 8900 !

Gonna throw some downloads at it now, Thank you for the help !

**Comment by OneCDOnly** [comment]
@apache6131 has also reported this as fixed: https://forum.qnap.com/viewtopic.php?p=763131#p763131
