### ISSUE TITLE
NZBGet: daemon NOT active

### ISSUE THREAD

**Issue by Sevyx** [OneCDOnly/sherpa#114]
Cant install Medusa for example becasue of missing /opt/bin/find, Anyone has any idea how to fix this?
```
* A mini package manager to install various media-management apps into QNAP NAS
     1  [ dbug ] (II) ========================================================================
     2  [ dbug ] (**) SCRIPT:             started: Wed Aug 26 14:27:34 CEST 2020
     3  [ dbug ] (**) SCRIPT:             version: 200826j
     4  [ dbug ] (**) SCRIPT:                 PID: 20682
     5  [ dbug ] (II) ------------------------------------------------------------------------
     6  [ dbug ] (II) Markers: (**) detected, (II) information, (WW) warning, (LL) log file,
     7  [ dbug ] (II)  (EE) error, (==) processing, (--) done, (>>) f entry, (<<) f exit,
     8  [ dbug ] (II)  (vv) variable name & value, ($1) positional argument value.
     9  [ dbug ] (II) ------------------------------------------------------------------------
    10  [ dbug ] (vv) $abort [true]
    11  [ dbug ] (vv) $error [true]
    12  [ fail ] A required NAS system file is missing (/opt/bin/find)
    13  [ dbug ] (**) NAS   :               model: TS-420
    14  [ dbug ] (**) NAS   :                 RAM: 515492 kB
    15  [ dbug ] (**) NAS   :    firmware version: 4.3.3
    16  [ dbug ] (**) NAS   :      firmware build: 20200611
    17  [ dbug ] (**) NAS   :              kernel: 3.4.6 armv5tel
    18  [ dbug ] (**) NAS   :           OS uptime: 50 min
    19  [ dbug ] (**) NAS   :         system load: 1 min=3.63, 5 min=3.53, 15 min=3.74
    20  [ dbug ] (**) NAS   :                USER: admin
    21  [ dbug ] (**) NAS   :                EUID: 0
    22  [ dbug ] (**) NAS   :      default volume: /share/MD0_DATA
    23  [ dbug ] (**) NAS   :               $PATH: /share/MD0_DATA/.qpkg/Python3/python3/bin:/
    24  [ dbug ] (**) NAS   :                /opt: <not present>
    25  [ dbug ] (**) NAS   :     /share/Download: MD0_DATA/Download
    26  [ dbug ] (**) SCRIPT:  unparsed arguments: Medusa
    27  [ dbug ] (**) SCRIPT:   app(s) to install: OMedusa 
    28  [ dbug ] (**) SCRIPT: app(s) to uninstall:  
    29  [ dbug ] (**) SCRIPT: app(s) to reinstall:  
    30  [ dbug ] (**) SCRIPT:    app(s) to update:  
    31  [ dbug ] (**) SCRIPT:    app(s) to backup:  
    32  [ dbug ] (**) SCRIPT:   app(s) to restore:  
    33  [ dbug ] (**) SCRIPT:           work path: /share/Public/sherpa.tmp
    34  [ dbug ] (**) QPKG  :       download path: /share/Public/sherpa.tmp/qpkg.downloads
    35  [ dbug ] (**) IPKG  :       download path: /share/Public/sherpa.tmp/ipkg.downloads
    36  [ dbug ] (**) QPKG  :                arch: none
    37  [ dbug ] (II) ------------------------------------------------------------------------
    38  [ fail ] 'OMedusa' install failed! [0]
    39  [ dbug ] (vv) $suggest_issue [true]
    40  [ dbug ] (II) ------------------------------------------------------------------------
    41  [ dbug ] (**) SCRIPT:            finished: Wed Aug 26 14:27:35 CEST 2020
    42  [ dbug ] (**) SCRIPT:        elapsed time: 00h:00m:01s
    43  [ dbug ] (II) ========================================================================
    44  [ dbug ] (II) ========================================================================
    45  [ dbug ] (**) SCRIPT:             started: Wed Aug 26 14:28:11 CEST 2020
    46  [ dbug ] (**) SCRIPT:             version: 200826j
    47  [ dbug ] (**) SCRIPT:                 PID: 21599
    48  [ dbug ] (II) ------------------------------------------------------------------------
    49  [ dbug ] (II) Markers: (**) detected, (II) information, (WW) warning, (LL) log file,
    50  [ dbug ] (II)  (EE) error, (==) processing, (--) done, (>>) f entry, (<<) f exit,
    51  [ dbug ] (II)  (vv) variable name & value, ($1) positional argument value.
    52  [ dbug ] (II) ------------------------------------------------------------------------
    53  [ dbug ] (vv) $abort [true]
    54  [ dbug ] (vv) $logview_only [true]
```

**Comment by bruensb** [comment]
Hi Sevyx, you closed the issue. Was it solved? How?

**Comment by Sevyx** [comment]
Solved this part, Python 2 was stil in the way had to set python3 manually.

However got medusa to work but my NZBGET stil says No deamon running when i try to start it. 

[/share/MD0_DATA/.qpkg/NZBGet] # sh nzbget.sh start
= daemon is not active
* starting daemon: OK
= daemon is not active

So looks like it is crashing straight away.

**Comment by OneCDOnly** [comment]
@Sevyx can you please reinstall the NZBGet package via sherpa? I've fixed a lots of bugs in the service scripts in the last week or-so. I wouldn't trust those old scripts. 😉

**Comment by Sevyx** [comment]
That didnt go as planned. 

500 dbug: (II) ============================================================================
    501 dbug: (**)    SCRIPT:             started: Thu Aug 27 10:28:40 CEST 2020
    502 dbug: (**)    SCRIPT:             version: 200827t
    503 dbug: (**)    SCRIPT:                 PID: 30509
    504 dbug: (II) ----------------------------------------------------------------------------
    505 dbug: (II) Markers: (**) detected, (II) information, (WW) warning, (LL) log file,
    506 dbug: (II)  (EE) error, (==) processing, (--) done, (>>) f entry, (<<) f exit,
    507 dbug: (II)  (vv) variable name & value, ($1) positional argument value.
    508 dbug: (II) ----------------------------------------------------------------------------
    509 dbug: (**)  HARDWARE:               model: TS-420
    510 dbug: (**)  HARDWARE:                 RAM: 515492 kB
    511 dbug: (**)  FIRMWARE:    firmware version: 4.3.3
    512 dbug: (**)  FIRMWARE:      firmware build: 20200611
    513 dbug: (**)  FIRMWARE:              kernel: 3.4.6 armv5tel
    514 dbug: (**) USERSPACE:           OS uptime: 20:51
    515 dbug: (**) USERSPACE:         system load: 1 min=3.63, 5 min=3.25, 15 min=3.12
    516 dbug: (**) USERSPACE:               $USER: admin
    517 dbug: (**) USERSPACE:               $EUID: 0
    518 dbug: (**) USERSPACE:      default volume: /share/MD0_DATA
    519 dbug: (**) USERSPACE:               $PATH: /opt/bin:/opt/sbin:/bin:/sbin:/usr/bin:/usr
    520 dbug: (**) USERSPACE:                /opt: /share/MD0_DATA/.qpkg/Entware
    521 dbug: (**) USERSPACE:       Python 3 path: /opt/bin/python3
    522 dbug: (**) USERSPACE:    Python 3 version: Python 3.8.3
    523 dbug: (**) USERSPACE:     /share/Download: MD0_DATA/Download
    524 dbug: (**)    SCRIPT:  unparsed arguments: NZBGet
    525 dbug: (**)    SCRIPT:   app(s) to install: NZBGet 
    526 dbug: (**)    SCRIPT: app(s) to uninstall:  
    527 dbug: (**)    SCRIPT: app(s) to reinstall:  
    528 dbug: (**)    SCRIPT:    app(s) to update:  
    529 dbug: (**)    SCRIPT:    app(s) to backup:  
    530 dbug: (**)    SCRIPT:   app(s) to restore:  
    531 dbug: (**)    SCRIPT:           work path: /share/Public/sherpa.tmp
    532 dbug: (**)      QPKG:       download path: /share/Public/sherpa.tmp/qpkg.downloads
    533 dbug: (**)      IPKG:       download path: /share/Public/sherpa.tmp/ipkg.downloads
    534 dbug: (**)      QPKG:                arch: none
    535 note: An upgraded package is available for ESC[1;33mNZBGetESC[0m
    536 dbug: (**)      QPKG:   Entware installer: std
    537 dbug: (II) ----------------------------------------------------------------------------
    538 dbug: (>>) DownloadQPKGs()
    539 dbug: (>>) DownloadQPKG()
    540 proc: downloading QPKG (NZBGet_200827.qpkg) ...
    541 done: downloaded QPKG (NZBGet_200827.qpkg)
    542 dbug: (<<) DownloadQPKG() [0]
    543 dbug: (<<) DownloadQPKGs() [0]
    544 dbug: (**)      QPKG:           'Optware': not installed [250]
    545 dbug: (**)      QPKG:        'Entware-3x': not installed [250]
    546 dbug: (**)      QPKG:        'Entware-ng': not installed [250]
    547 dbug: (>>) InstallQPKGIndeps()
    548 dbug: (II) patch: do the "opt shuffle" - already done
    549 dbug: (<<) InstallQPKGIndeps() [0]
    550 dbug: (>>) InstallQPKGIndepsAddons()
    551 dbug: (>>) InstallIPKGs()
    552 proc: updating 'Entware' package list ...
    553 done: updated 'Entware' package list
    554 dbug: (>>) InstallIPKGBatch()
    555 dbug: (II) ----------------------------------------------------------------------------
556 dbug: (**)     STAGE:   start stage timer
    557 proc: determining IPKGs required ...
    558 dbug: (II) IPKGs requested: ca-certificates git git-http less mediainfo nano nzbget python3 python3-pip python3-pyopenssl sed
    559 dbug: (==) finding IPKG dependencies ...
    560 dbug: (--) complete
    561 dbug: (II) found all IPKG dependencies in 13 iterations
    562 dbug: (II) IPKGs requested + dependencies: ca-bundle ca-certificates ca-certs file git git-http less libbz2 libc libcurl libdb47 libexpat libffi libgcc libgdbm liblzma lib    562 magic libncurses libncursesw libopenssl libpcre libpthread librt libsqlite3 libssp libstdcpp libtirpc libuuid libxml2 mediainfo nano nzbget python-pip-conf python3 python3    562 -asyncio python3-base python3-cffi python3-cgi python3-cgitb python3-codecs python3-cryptography python3-ctypes python3-dbm python3-decimal python3-distutils python3-email    562  python3-gdbm python3-light python3-logging python3-lzma python3-multiprocessing python3-ncurses python3-openssl python3-pip python3-pkg-resources python3-ply python3-pycp    562 arser python3-pydoc python3-pyopenssl python3-setuptools python3-six python3-sqlite3 python3-unittest python3-urllib python3-xml sed terminfo zlib
    563 dbug: (**)     STAGE:        elapsed time: 00h:00m:10s
    564 dbug: (II) ----------------------------------------------------------------------------
    565 dbug: (==) excluding IPKGs already installed ...
    566 dbug: (--) complete
    567 dbug: (II) IPKGs to download: sed
    568 dbug: (==) determining size of IPKG to download ...
    569 dbug: (--) complete
    570 dbug: (vv) $IPKG_download_size [79906]
    571 done: 1 IPKG (80kB) to be downloaded
    572 dbug: (II) ----------------------------------------------------------------------------
    573 dbug: (**)     STAGE:   start stage timer
    574 proc: downloading & installing 1 IPKG ...
    575 done: downloaded & installed 1 IPKG
    576 dbug: (**)     STAGE:        elapsed time: 00h:00m:03s
    577 dbug: (II) ----------------------------------------------------------------------------
    578 dbug: (vv) $pip3_install [true]
    579 dbug: (<<) InstallIPKGBatch() [0]
    580 dbug: (<<) InstallIPKGs() [0]
    581 dbug: (>>) InstallPy3Modules()
    582 proc: downloading & installing 'Python 3' modules ...
    583 done: downloaded & installed 'Python 3' modules
    584 dbug: (<<) InstallPy3Modules() [0]
    585 dbug: (<<) InstallQPKGIndepsAddons() [0]
    586 dbug: (>>) InstallTargetQPKG()
    587 proc: installing QPKG (NZBGet_200827.qpkg) - this can take a while ...
    588 done: installed QPKG (NZBGet_200827.qpkg)
    589 dbug: (vv) $abort [true]
    590 dbug: (vv) $error [true]
    591 fail: 'NZBGet' service failed to start. Check (/var/log/NZBGet.log) for more information.
    592 dbug: (<<) InstallTargetQPKG() [0]
    593 fail: 'NZBGet' reinstall failed! [0].
    594 dbug: (vv) $suggest_issue [true]
    595 dbug: (II) ----------------------------------------------------------------------------
    596 dbug: (**)    SCRIPT:            finished: Thu Aug 27 10:29:42 CEST 2020
    597 dbug: (**)    SCRIPT:        elapsed time: 00h:01m:02s
    598 dbug: (II) ============================================================================

And the NZBLog:

-------------------- 'start' requested --------------------
= Thu Aug 27 10:51:23 CEST 2020, QPKG: 200827, application: 21.0
= daemon NOT active
* starting daemon: OK
* waiting for PID file to be created: OK
= daemon NOT active

**Comment by OneCDOnly** [comment]
> I see this running:
> 12584 admin 1972 S /opt/bin/nzbget --daemon --configfile /share/MD0_DATA/.qpkg/NZBGet/config/config.ini
> 
> Have to kill it, before i can restart it.

Does it now correctly restart via `/etc/init.d/nzbget.sh restart`?

**Comment by Sevyx** [comment]
Nope, when i kill it and restart/start:

starting daemon: OK
waiting for PID file to be created: OK
= daemon NOT active

**Comment by OneCDOnly** [comment]
OK, let's do some detective work. 🤓 

For the daemon to be considered "active" by the service script, [4 conditions must be met](https://github.com/OneCDOnly/sherpa/blob/128da2cb4f82e7b27ebdf2a7f7e613ecc3b4b8c5/QPKGs/NZBGet/shared/nzbget.sh#L427):

1. a daemon PID file exists (this can be found in `/opt/var/lock/nzbget.lock` and is created by NZBGet when it starts)
2. the PID contained within this file must be a live process (check this with `cat /opt/var/lock/nzbget.lock`), then compare it against your process list: `ps ax | grep $(</opt/var/lock/nzbget.lock)`
3. the `$TARGET_DAEMON` constant used in the service script needs to be not-null (this is hard-coded within the `nzbget.sh` service script as `/opt/bin/nzbget` so this should be fine)
4. the process mentioned earlier has launch-arguments. The name of the daemon (`/opt/bin/nzbget`)must be found within these arguments. Check this with `cat /proc/$(</opt/var/lock/nzbget.lock)/cmdline`.

If any of these 4 conditions are incorrect, the script will think NZBGet is not running. Can you please check them if you're able? 

Thank you.

**Comment by Sevyx** [comment]
./nzbget.sh start  
= daemon NOT active
* starting daemon: OK
* waiting for PID file to be created: OK
= daemon IS active: PID 27650
= daemon listening address: 
* checking for UI port 6789 response: (no-more than 20 seconds): 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, failed!
= App Center configuration updated with current port information
! no response on configured port(s)!


Thanks for your pointers mate. fixed it. The problem was with the Lock files. My system had a old NZBget install. That old install holded a Lock file. That caused for the new installation to crash when trying to make a daemon.

After removing all the old files including the Lock, solved it. Thanks for your background info about the Lock files. 

So:
done: installed QPKG (NZBGet_200827.qpkg)                                    
done: 'NZBGet' has been successfully reinstalled!

**Comment by OneCDOnly** [comment]
Good work. 😄 

Yes, it's nearly always the lock file that causes these issues. 🤣
