### ISSUE TITLE
A required NAS system file is missing (/opt/bin/find)

### ISSUE THREAD

**Issue by bruensb** [OneCDOnly/sherpa#115]
Installing a new NAS and repurposing the old NAS I want to reinstall SABnzbd using the sherpa script but I get the following error

A required NAS system file is missing (/opt/bin/find)

Going through the forum and github I could not find the solution and the funny thing is that only three hours ago I saw someone post the same issue and close it an hour later.

I've tried to install it on both NAS-ses and both have the same error. Log files for the new NAS below. Old NAS is the TX-253 Pro

dbug: (vv) $show_debugging [true]
dbug: (vv) $abort [true]
dbug: (vv) $error [true]
fail: A required NAS system file is missing (/opt/bin/find)
dbug: (**) NAS   :               model: TS-253D
dbug: (**) NAS   :                 RAM: 8050936 kB
dbug: (**) NAS   :    firmware version: 4.4.3
dbug: (**) NAS   :      firmware build: 20200817
dbug: (**) NAS   :              kernel: 4.14.24-qnap x86_64
dbug: (**) NAS   :           OS uptime: 1 day
dbug: (**) NAS   :         system load: 1 min=1.70, 5 min=1.90, 15 min=1.88
dbug: (**) NAS   :                USER: admin
dbug: (**) NAS   :                EUID: 0
dbug: (**) NAS   :      default volume: /share/CACHEDEV1_DATA
dbug: (**) NAS   :               $PATH: /bin:/sbin:/usr/bin:/usr/sbin:/usr/bin/X                                                                          11:
dbug: (**) NAS   :                /opt: <not present>
dbug: (**) NAS   :     /share/Download: CACHEDEV1_DATA/Download
dbug: (**) SCRIPT:  unparsed arguments: SABnzbd --debug
dbug: (**) SCRIPT:   app(s) to install: SABnzbd
dbug: (**) SCRIPT: app(s) to uninstall:
dbug: (**) SCRIPT: app(s) to reinstall:
dbug: (**) SCRIPT:    app(s) to update:
dbug: (**) SCRIPT:    app(s) to backup:
dbug: (**) SCRIPT:   app(s) to restore:
dbug: (**) SCRIPT:           work path: /share/Public/sherpa.tmp
dbug: (**) QPKG  :       download path: /share/Public/sherpa.tmp/qpkg.downloads
dbug: (**) IPKG  :       download path: /share/Public/sherpa.tmp/ipkg.downloads
dbug: (**) QPKG  :                arch: x64
dbug: (II) ---------------------------------------------------------------------                                                                          ---
fail: 'SABnzbd' install failed! :S [0]                                                                                                                    
dbug: (vv) $suggest_issue [true]

* Please consider creating a new issue for this on GitHub:
        https://github.com/OneCDOnly/sherpa/issues

* Alternatively, post on the QNAP NAS Community Forum:
        https://forum.qnap.com/viewtopic.php?f=320&t=132373

* Remember to include a copy of your sherpa log for analysis.

- View the sherpa log:
        ./sherpa.sh --log

- Upload the sherpa log to a public pastebin (https://termbin.com):
        ./sherpa.sh --paste
dbug: (II) ---------------------------------------------------------------------                                                                          ---
dbug: (**) SCRIPT:            finished: Wed Aug 26 17:17:52 CEST 2020
dbug: (**) SCRIPT:        elapsed time: 00h:00m:01s
dbug: (II) =====================================================================                                                                          ===

**Comment by OneCDOnly** [comment]
Hi @bruensb I've found the problem and now fixed it. Please try your install again.
