### ISSUE TITLE
LazyLibrarian is moving

### ISSUE THREAD

**Issue by philborman** [OneCDOnly/sherpa#13]
Hi,

Just a heads-up, on Saturday (10 Nov) we will be moving the repo to

https://gitlab.com/LazyLibrarian/LazyLibrarian.git

The github/dobytang one will be mothballed as dobytang is no longer around and we cannot get full access rights to it.  We would have liked the LazyLibrarian group at github as that's inactive but the owner hasn't responded to requests to release it, so we're moving to gitlab.

The new location also has a brand new much needed documentation section, and we hope to include automated builds of deb rpm and snap packages.

Many thanks for your support of lazylibrarian

Phil.

**Comment by OneCDOnly** [comment]
Thanks for the heads-up Phil. :)
