### ISSUE TITLE
How to install CURL?

### ISSUE THREAD

**Issue by Rumik** [OneCDOnly/sherpa#131]
Hey there... my QNAP doesn't seem to have CURL installed. Can anyone tell me how to install it so I can install Sherpa?

Thanks!

**Comment by OneCDOnly** [comment]
Hi @Rumik

Hmm.. `curl` is built-in to QTS. What do you see when you run this command?
```
type -a curl
```

**Comment by Rumik** [comment]
It says: -a: command not found

:(

**Comment by OneCDOnly** [comment]
Can you please post your exact syntax? Linux filenames are case-sensitive, and I just want to ensure you're using the correct character-case. 😉

**Comment by OneCDOnly** [comment]
@Rumik also please note that the actual command string to type at the prompt literally starts with the word 'type'.

**Comment by Rumik** [comment]
Ha, that helped! :P

[~] # type -a curl
-sh: type: curl: not found

Thanks

**Comment by OneCDOnly** [comment]
No worries. 👍🏽 

Hmm... let's check your sbin location:
```
ll /sbin
```
You should see a long list of filenames. Please copypaste back what you can.

**Comment by Rumik** [comment]
Thanks for your help 👍 

[~] # head -n6 /etc/config/uLinux.conf
-sh: head: command not found

lrwxrwxrwx  1 admin administrators    7 2020-09-14 01:05 qreg -> nasutil*
-rwxr-xr-x  1 admin administrators 5.9K 2020-07-28 21:39 qr_generator*
lrwxrwxrwx  1 admin administrators   19 2020-09-14 01:05 qrm -> /usr/local/sbin/qrm*
lrwxrwxrwx  1 admin administrators   34 2020-09-14 00:07 qs_cmd -> /mnt/ext/opt/netmgr/util/qs_cmd.sh*
-rwxr-xr-x  1 admin administrators  35K 2020-07-28 21:39 qShield*
lrwxrwxrwx  1 admin administrators   37 2020-09-14 00:07 qs_util -> /mnt/ext/opt/netmgr/util/qs_utilv2.sh*
lrwxrwxrwx  1 admin administrators   58 2020-09-14 00:07 qs_util_ext -> /mnt/ext/opt/netmgr/api/qs_util_ext/qs_util_ext_gateway.py*
lrwxrwxrwx  1 admin administrators   37 2020-09-14 00:07 qs_utilv2 -> /mnt/ext/opt/netmgr/util/qs_utilv2.sh*
lrwxrwxrwx  1 admin administrators   22 2020-09-14 00:12 qsync_log_tool -> /sbin/qsyncsrv_busybox*
lrwxrwxrwx  1 admin administrators   61 2020-09-14 00:12 qsyncsrv_busybox -> /share/CACHEDEV1_DATA/.qpkg/QsyncServer/util/qsyncsrv_busybox*
lrwxrwxrwx  1 admin administrators   63 2020-09-14 00:12 qsyncsrv_c_log_cli -> /share/CACHEDEV1_DATA/.qpkg/QsyncServer/util/qsyncsrv_c_log_cli*
lrwxrwxrwx  1 admin administrators   60 2020-09-14 00:12 qsyncsrv_c_logd -> /share/CACHEDEV1_DATA/.qpkg/QsyncServer/util/qsyncsrv_c_logd*
lrwxrwxrwx  1 admin administrators   54 2020-09-14 00:12 qsyncsrvd -> /share/CACHEDEV1_DATA/.qpkg/QsyncServer/util/qsyncsrvd*
lrwxrwxrwx  1 admin administrators   57 2020-09-14 00:12 qsyncsrv_dbm -> /share/CACHEDEV1_DATA/.qpkg/QsyncServer/util/qsyncsrv_dbm*
lrwxrwxrwx  1 admin administrators   61 2020-09-14 00:12 qsyncsrv_dbm_cli -> /share/CACHEDEV1_DATA/.qpkg/QsyncServer/util/qsyncsrv_dbm_cli*
lrwxrwxrwx  1 admin administrators   61 2020-09-14 00:12 qsyncsrv_make_id -> /share/CACHEDEV1_DATA/.qpkg/QsyncServer/util/qsyncsrv_make_id*
lrwxrwxrwx  1 admin administrators   57 2020-09-14 00:12 qsyncsrv_man -> /share/CACHEDEV1_DATA/.qpkg/QsyncServer/util/qsyncsrv_man*
lrwxrwxrwx  1 admin administrators   69 2020-09-14 00:12 qsyncsrv_mariadb_initial -> /share/CACHEDEV1_DATA/.qpkg/QsyncServer/util/qsyncsrv_mariadb_initial*
lrwxrwxrwx  1 admin administrators   59 2020-09-14 00:12 qsyncsrv_metad -> /share/CACHEDEV1_DATA/.qpkg/QsyncServer/util/qsyncsrv_metad*
lrwxrwxrwx  1 admin administrators   63 2020-09-14 00:12 qsyncsrv_migration -> /share/CACHEDEV1_DATA/.qpkg/QsyncServer/util/qsyncsrv_migration*
lrwxrwxrwx  1 admin administrators   22 2020-09-14 00:12 qsyncsrv_online_user_util -> /sbin/qsyncsrv_busybox*
lrwxrwxrwx  1 admin administrators   22 2020-09-14 00:12 qsyncsrv_token_util -> /sbin/qsyncsrv_busybox*
lrwxrwxrwx  1 admin administrators   22 2020-09-14 00:12 qsyncsrv_tool -> /sbin/qsyncsrv_busybox*
lrwxrwxrwx  1 admin administrators   22 2020-09-14 00:12 qsyncsrv_util -> /sbin/qsyncsrv_busybox*
lrwxrwxrwx  1 admin administrators    7 2020-09-14 01:05 qsyscmd -> nasutil*
-rwxr-xr-x  1 admin administrators  20K 2020-07-28 21:39 qsyslogd*
-r-xr-xr-x  1 admin administrators  70K 2020-07-28 21:39 quota*
-r-xr-xr-x  1 admin administrators  83K 2020-07-28 21:39 quotacheck*
lrwxrwxrwx  1 admin administrators   13 2020-09-14 01:05 quotaoff -> /sbin/quotaon*
-r-xr-xr-x  1 admin administrators  61K 2020-07-28 21:39 quotaon*
-rwxr-xr-x  1 admin administrators 8.1K 2020-07-28 21:39 qwatchdogd*
lrwxrwxrwx  1 admin administrators    7 2020-09-14 01:05 radius_util -> nasutil*
-rwxr-xr-x  1 admin administrators 5.1K 2020-07-28 21:39 random_mac_addr*
-rwxr-xr-x  1 admin administrators 9.3K 2020-07-28 21:39 rcvy_share*
lrwxrwxrwx  1 admin administrators   16 2020-09-14 01:05 rdnssd -> /usr/sbin/rdnssd*
lrwxrwxrwx  1 admin administrators   12 2020-09-14 01:05 reboot -> /bin/busybox*
-rwxr-xr-x  1 admin administrators  11K 2020-07-28 21:39 reconnect_util*
-rwxr-xr-x  1 admin administrators  13K 2020-07-28 21:39 recycled*
lrwxrwxrwx  1 admin administrators    7 2020-09-14 01:05 regen_quota_conf -> nasutil*
lrwxrwxrwx  1 admin administrators    7 2020-09-14 01:05 _remove -> nasutil*
-r-xr-xr-x  1 admin administrators  61K 2020-07-28 21:39 repquota*
lrwxrwxrwx  1 admin administrators    7 2020-09-14 01:05 reset_admin_passwd -> nasutil*
lrwxrwxrwx  1 admin administrators    7 2020-09-14 01:05 reset_all -> nasutil*
lrwxrwxrwx  1 admin administrators    7 2020-09-14 01:05 reset_system -> nasutil*
lrwxrwxrwx  1 admin administrators   12 2020-09-14 01:05 resize2fs -> resize2fs_64*
-rwxr-xr-x  1 admin administrators 239K 2020-07-28 21:39 resize2fs_64*
-rwxr-xr-x  1 admin administrators  24K 2020-07-28 21:39 rfsd*
-rwxr-xr-x  1 admin administrators 5.9K 2020-07-28 21:39 rmcfg*
lrwxrwxrwx  1 admin administrators   12 2020-09-14 01:05 rmmod -> /bin/busybox*
lrwxrwxrwx  1 admin administrators   12 2020-09-14 01:05 route -> /bin/busybox*
lrwxrwxrwx  1 admin administrators    7 2020-09-14 01:05 rsync_util -> nasutil*
lrwxrwxrwx  1 admin administrators    7 2020-09-14 01:05 rsyslog_util -> nasutil*
-rwxr-xr-x  1 admin administrators 622K 2020-07-28 21:39 sas2flash*
-rwxr-xr-x  1 admin administrators 642K 2020-07-28 21:39 sas3flash*
-rwxr-xr-x  1 admin administrators  23K 2020-07-28 21:39 sas_jbod_util*
-rwxr-xr-x  1 admin administrators  15K 2020-07-28 21:39 sas_updater*
lrwxrwxrwx  1 admin administrators    7 2020-09-14 01:05 scanafpdb -> nasutil*
-rwxr-xr-x  1 admin administrators  21K 2020-07-28 21:39 sdmd*
-rwxr-xr-x  1 admin administrators 400K 2020-07-28 21:39 sedutil-cli*
lrwxrwxrwx  1 admin administrators    7 2020-09-14 01:05 send_alert_mail -> nasutil*
lrwxrwxrwx  1 admin administrators    7 2020-09-14 01:05 send_antivirus_alert_mail -> nasutil*
lrwxrwxrwx  1 admin administrators    7 2020-09-14 01:05 send_queue_mail -> nasutil*
lrwxrwxrwx  1 admin administrators    7 2020-09-14 01:05 set_all_online_user_quota -> nasutil*
-rwxr-xr-x  1 admin administrators 6.9K 2020-07-28 21:39 setcfg*
lrwxrwxrwx  1 admin administrators    7 2020-09-14 01:05 set_home_directory -> nasutil*
lrwxrwxrwx  1 admin administrators    8 2020-09-14 01:05 set_ipupatetime -> get_time*
-rwxr-xr-x  1 admin administrators  21K 2020-07-28 21:39 setpci*
-r-xr-xr-x  1 admin administrators  69K 2020-07-28 21:39 setquota*
lrwxrwxrwx  1 admin administrators    7 2020-09-14 01:05 setsum -> nasutil*
lrwxrwxrwx  1 admin administrators    7 2020-09-14 01:05 set_volume_mode -> nasutil*
-rwxr-xr-x  1 admin administrators  69K 2020-07-28 21:39 sginfo*
-rwxr-xr-x  1 admin administrators  80K 2020-07-28 21:39 sg_inq*
-rwxr-xr-x  1 admin administrators  89K 2020-07-28 21:39 sg_logs*
-rwxr-xr-x  1 admin administrators  16K 2020-07-28 21:39 sg_raw*
-rwxr-xr-x  1 admin administrators  17K 2020-07-28 21:39 sg_readcap*
-rwxr-xr-x  1 admin administrators  12K 2020-07-28 21:39 sg_requests*
-rwxr-xr-x  1 admin administrators  20K 2020-07-28 21:39 sg_senddiag*
-rwxr-xr-x  1 admin administrators  68K 2020-07-28 21:39 sg_ses*
-rwxr-xr-x  1 admin administrators  16K 2020-07-28 21:39 sg_start*
-rwxr-xr-x  1 admin administrators  14K 2020-07-28 21:39 sg_write_buffer*
-rwxr-xr-x  1 admin administrators 698K 2020-07-28 21:39 sln*
lrwxrwxrwx  1 admin administrators   24 2020-09-14 01:05 smbtools -> /usr/local/sbin/smbtools*
-rwxr-xr-x  1 admin administrators 8.3K 2020-07-28 21:39 snapshot_util*
-rwxr-xr-x  1 admin administrators  25K 2020-07-28 21:39 SSDcacheutil*
lrwxrwxrwx  1 admin administrators    7 2020-09-14 01:05 sss_convert -> nasutil*
-rwxr-xr-x  1 admin administrators  51K 2020-07-28 21:39 storage_util*
lrwxrwxrwx  1 admin administrators   23 2020-09-14 01:05 stx_ihm -> /usr/local/sbin/stx_ihm*
lrwxrwxrwx  1 admin administrators   12 2020-09-14 01:05 swapoff -> /bin/busybox*
lrwxrwxrwx  1 admin administrators   12 2020-09-14 01:05 swapon -> /bin/busybox*
lrwxrwxrwx  1 admin administrators   12 2020-09-14 01:05 sysctl -> /bin/busybox*
lrwxrwxrwx  1 admin administrators   12 2020-09-14 01:05 syslogd -> /bin/busybox*
lrwxrwxrwx  1 admin administrators   28 2020-09-14 01:05 syslog_maild -> /usr/local/sbin/syslog_maild*
lrwxrwxrwx  1 admin administrators   12 2020-09-14 01:05 test -> /bin/busybox*
lrwxrwxrwx  1 admin administrators   17 2020-09-14 01:05 thin_check -> thintools_bsadapt*
lrwxrwxrwx  1 admin administrators   17 2020-09-14 01:05 thin_dump -> thintools_bsadapt*
lrwxrwxrwx  1 admin administrators   17 2020-09-14 01:05 thin_repair -> thintools_bsadapt*
-rwxr-xr-x  1 admin administrators 6.9K 2020-07-28 21:39 thintools_bsadapt*
lrwxrwxrwx  1 admin administrators    7 2020-09-14 01:05 tm_quota_check -> nasutil*
lrwxrwxrwx  1 admin administrators   12 2020-09-14 01:05 traceroute -> /bin/busybox*
lrwxrwxrwx  1 admin administrators    7 2020-09-14 01:05 transfer_nfs_setting -> nasutil*
lrwxrwxrwx  1 admin administrators   10 2020-09-14 01:05 tune2fs -> tune2fs_64*
-rwxr-xr-x  1 admin administrators 320K 2020-07-28 21:39 tune2fs_64*
-rwxr-xr-x  1 admin administrators  24K 2020-07-28 21:39 txscan*
-rwxr-xr-x  1 admin administrators 112K 2020-07-28 21:39 udevadm*
-rwxr-xr-x  1 admin administrators 104K 2020-07-28 21:39 udevd*
lrwxrwxrwx  1 admin administrators    7 2020-09-14 01:05 umount_all_extdev -> nasutil*
lrwxrwxrwx  1 admin administrators    7 2020-09-14 01:05 umount_all_vdd -> nasutil*
lrwxrwxrwx  1 admin administrators    7 2020-09-14 01:05 umount_nfs_mp -> nasutil*
lrwxrwxrwx  1 admin administrators   12 2020-09-14 01:05 unix2dos -> /bin/busybox*
lrwxrwxrwx  1 admin administrators    7 2020-09-14 01:05 update_krb5_ticket -> nasutil*
-rwxr-xr-x  1 admin administrators  18K 2020-07-28 20:07 upgrade_pool.sh*
-rwxr-xr-x  1 admin administrators  10K 2020-07-28 21:39 upgrade_qos_shortcut*
-rwxr-xr-x  1 admin administrators  25K 2020-07-28 21:39 upnpcd*
-rwxr-xr-x  1 admin administrators  40K 2020-07-28 21:39 upnpd*
lrwxrwxrwx  1 admin administrators   14 2020-09-14 01:05 upsc -> /usr/sbin/upsc*
-rwxr-xr-x  1 admin administrators 7.9K 2020-07-28 21:39 ups_snmptrap_handler*
-rwxr-xr-x  1 admin administrators  16K 2020-07-28 21:39 ups_yec*
-rwxr-xr-x  1 admin administrators 6.6K 2020-07-28 21:39 usbtest*
lrwxrwxrwx  1 admin administrators    7 2020-09-14 01:05 user_add -> nasutil*
-rwxr-xr-x  1 admin administrators  60K 2020-07-28 21:39 user_cmd*
lrwxrwxrwx  1 admin administrators    7 2020-09-14 01:05 user_del -> nasutil*
lrwxrwxrwx  1 admin administrators    7 2020-09-14 01:05 user_expiry -> nasutil*
lrwxrwxrwx  1 admin administrators    7 2020-09-14 01:05 user_group_util -> nasutil*
lrwxrwxrwx  1 admin administrators    7 2020-09-14 01:05 user_status -> nasutil*
lrwxrwxrwx  1 admin administrators    7 2020-09-14 01:05 utilization_util -> nasutil*
lrwxrwxrwx  1 admin administrators   10 2020-09-14 01:05 uuidgen -> uuidgen_64*
-rwxr-xr-x  1 admin administrators  16K 2020-07-28 21:39 uuidgen_64*
lrwxrwxrwx  1 admin administrators   27 2020-09-14 01:05 vdd_control -> /usr/local/sbin/vdd_control*
lrwxrwxrwx  1 admin administrators    7 2020-09-14 01:05 verify_2sv -> nasutil*
-rwxr-xr-x  1 admin administrators  37K 2020-07-28 21:39 veritysetup*
lrwxrwxrwx  1 admin administrators   60 2020-09-14 00:12 version_cleaner -> /share/CACHEDEV1_DATA/.qpkg/QsyncServer/util/version_cleaner*
lrwxrwxrwx  1 admin administrators   53 2020-09-14 00:12 versiond -> /share/CACHEDEV1_DATA/.qpkg/QsyncServer/util/versiond*
lrwxrwxrwx  1 admin administrators    3 2020-09-14 01:05 vgcfgbackup -> lvm*
lrwxrwxrwx  1 admin administrators    3 2020-09-14 01:05 vgcfgrestore -> lvm*
lrwxrwxrwx  1 admin administrators    3 2020-09-14 01:05 vgchange -> lvm*
lrwxrwxrwx  1 admin administrators    3 2020-09-14 01:05 vgck -> lvm*
lrwxrwxrwx  1 admin administrators    3 2020-09-14 01:05 vgconvert -> lvm*
lrwxrwxrwx  1 admin administrators    3 2020-09-14 01:05 vgcreate -> lvm*
lrwxrwxrwx  1 admin administrators    3 2020-09-14 01:05 vgdisplay -> lvm*
lrwxrwxrwx  1 admin administrators    3 2020-09-14 01:05 vgexport -> lvm*
lrwxrwxrwx  1 admin administrators    3 2020-09-14 01:05 vgextend -> lvm*
lrwxrwxrwx  1 admin administrators    3 2020-09-14 01:05 vgimport -> lvm*
lrwxrwxrwx  1 admin administrators    3 2020-09-14 01:05 vgmerge -> lvm*
lrwxrwxrwx  1 admin administrators    3 2020-09-14 01:05 vgmknodes -> lvm*
lrwxrwxrwx  1 admin administrators    3 2020-09-14 01:05 vgreduce -> lvm*
lrwxrwxrwx  1 admin administrators    3 2020-09-14 01:05 vgremove -> lvm*
lrwxrwxrwx  1 admin administrators    3 2020-09-14 01:05 vgrename -> lvm*
lrwxrwxrwx  1 admin administrators    3 2020-09-14 01:05 vgs -> lvm*
lrwxrwxrwx  1 admin administrators    3 2020-09-14 01:05 vgscan -> lvm*
lrwxrwxrwx  1 admin administrators    3 2020-09-14 01:05 vgsplit -> lvm*
lrwxrwxrwx  1 admin administrators   23 2020-09-14 01:05 vhost_cmd.php -> /usr/sbin/vhost_cmd.php*
lrwxrwxrwx  1 admin administrators    7 2020-09-14 01:05 vjbod_util -> nasutil*
-rwxr-xr-x  1 admin administrators  13K 2020-07-28 21:39 vpd_util*
lrwxrwxrwx  1 admin administrators    7 2020-09-14 01:05 vpn_check_account -> nasutil*
lrwxrwxrwx  1 admin administrators    7 2020-09-14 01:05 vpn_util -> nasutil*
lrwxrwxrwx  1 admin administrators    7 2020-09-14 01:05 vs_refresh -> nasutil*
lrwxrwxrwx  1 admin administrators    8 2020-09-14 01:05 wfm_log_tool -> log_tool*
-rwxr-xr-x  1 admin administrators 2.9K 2020-07-28 19:21 wpascript.sh*
lrwxrwxrwx  1 admin administrators    7 2020-09-14 01:05 write_log -> nasutil*
lrwxrwxrwx  1 admin administrators   23 2020-09-14 00:09 wsd.py -> /mnt/ext/opt/wsd/wsd.py
-rwxr-xr-x  1 admin administrators  83K 2020-07-28 21:39 xtables-multi*
-rwxr-xr-x  1 admin administrators  15K 2020-07-28 21:39 zdump*
-rwxr-xr-x  1 admin administrators  43K 2020-07-28 21:39 zic*
[~] #

**Comment by OneCDOnly** [comment]
@Rumik I'll admit, I don't know what's going on with your NAS. 😕 

If it's missing a basic utility like `head`, then it appears to have some major issues. I can't diagnose these remotely. 

Suggest you stay with the GUI-only packages and avoid sherpa until your QTS is running correctly.

**Comment by Rumik** [comment]
Okay, thanks for your help! How strange!
