### ISSUE TITLE
main: crash when reinstalling Entware

### ISSUE THREAD

**Issue by OneCDOnly** [OneCDOnly/sherpa#132]
reported here: https://forum.qnap.com/viewtopic.php?p=764722#p764722
```
[/share/Public] # ./sherpa.sh reinstall ew
sherpa.sh 200914 • a mini-package-manager for QNAP NAS

note: Upgraded packages are available for SABnzbd, nzbToMedia, SickChill
done: downloaded QPKG (Entware_1.02std.qpkg)
note: Reinstalling 'Entware' will remove all IPKGs and Python modules, and only those required to support your sherpa apps will be reinstalled.
note: Your installed IPKG list will be saved to (/share/Public/opkg.prev.installed.list)
note: Your installed Python module list will be saved to (/share/Public/pip3.prev.installed.list)
quiz: Press 'Y' to remove all current 'Entware' IPKGs (and their configurations)quiz: Press 'Y' to remove all current 'Entware' IPKGs (and their configurations), or any other key to abort: y
done: package and Python module lists saved
done: uninstalled 'Entware'
grep: : No such file or directory
sed: : No such file or directory
sed: : No such file or directory
fail: A required NAS system file is missing (/opt/bin/opkg)
```

**Comment by ricounet67** [comment]
I have the same issue : fail: A required NAS system file is missing (/opt/bin/opkg): aborting ...
I just reinstalled the last version of sherpa 201114 and when I try to install a package I have this error

**Comment by OneCDOnly** [comment]
Hi @ricounet67 can you please post your sherpa log so I can see your configuration?

**Comment by ricounet67** [comment]
I finally succeeded to make it work by reinstalling Sherpa. I also had the old versions of Entware installed. Maybe it was a part of the problem. So I removed all the Entware packages and Sherpa before reinstalling Sherpa from Applications manager, then with SSH connexion made a Sherpa --install-all
At the end everything seems to work fine
