### ISSUE TITLE
manager: "Unable to create file descriptor"

### ISSUE THREAD

**Issue by r6ual** [OneCDOnly/sherpa#135]
SickChill Install failed with titled error.

Debug [https://l.termbin.com/70em](https://l.termbin.com/70em)

**Comment by OneCDOnly** [comment]
Hi @r6ual thanks for reporting this. 👍🏽 

Your's is the third time this has happened recently while installing SickChill. I'm unable to replicate the fault at my end, so I've been guessing as to the cause of this problem and trying to code accordingly. 

I don't know what's causing this, but I'll make some mods today and post back when they're ready. 

In the interim, have you tried installing SickChill a second time (just in case this was a temporary error)?

**Comment by OneCDOnly** [comment]
@r6ual I've just pushed a commit that may fix this. Can you please wait for 10 minutes from the time of this post, then try your SickChill installation again?

**Comment by r6ual** [comment]
Id say thats a win, has pulled the qpkg from the github repo ok. One thing I will say though, and not sure if this is by design (although Im guessing not), is that, and I tried it 3 times for confirmation, is that after the initial install of the qpkg installs OK, I had to manually run the `sickchill.sh start` to initialise git to pull the actual sickchill github code files and subsequently start up the app.  i.e Without the manual running of `sickchill.sh start`, it does not proceed to pull the git. Personally doesnt phase me too much but if you're after fully automation of the install.. then for me at least , that little tidbit remains albeit a diff issue I guess.. 

Thanks for your help.

**Comment by OneCDOnly** [comment]
> One thing I will say though, and not sure if this is by design (although Im guessing not), is that, and I tried it 3 times for confirmation, is that after the initial install of the qpkg installs OK, I had to manually run the `sickchill.sh start` to initialise git to pull the actual sickchill github code files and subsequently start up the app. i.e Without the manual running of `sickchill.sh start`, it does not proceed to pull the git. 

Ah, that's supposed to happen automatically. 😕 

What does the SickChill service log say at the time SickChill was installed?

**Comment by OneCDOnly** [comment]
@r6ual just had an idea: did you refresh the App Center screen after installing SickChill via sherpa? This screen refresh doesn't happen dynamically, so you might have been looking at a disabled SickChill icon that was out-of-date. Thoughts?

**Comment by OneCDOnly** [comment]
> Ah, that's supposed to happen automatically. A `start` operation is the standard behaviour for QTS after installing a QPKG. 

Although, I forgot to mention that a package is only started after a reinstall if it wasn't in a disabled state. Disabled means a greyed-out icon in App Center. 

This means packages can be reinstalled or upgraded and ensure they don't spontaneously startup again after a CLI update. It's by-design.

These damn computers are getting too clever. 😉
