### ISSUE TITLE
sherpa error: no /usr/bin/sort

### ISSUE THREAD

**Issue by ricounet67** [OneCDOnly/sherpa#138]
When I launch the sherpa command, I have the following error:
[~] # sherpa
fail: A required NAS system file is missing (/usr/bin/sort)
/share/sherpa.manager.sh: line 2497: Session.LineSpace.Clear: command not found
/share/sherpa.manager.sh: line 3097: Session.Abort.Set: command not found
/share/sherpa.manager.sh: line 3815: Session.Debug.To.Screen.IsSet: command not found

Then it is impossible to use sherpa.
My NAS is a TS 228-A with a 4.4.3.1421 microcode version.

**Comment by OneCDOnly** [comment]
Hi @ricounet67 this happens sometimes with QTS. 

Can you please run this to restore the sort symlink? 
```
ln -s /bin/busybox /usr/bin/sort
```

**Comment by ricounet67** [comment]
Yes it solves the problem 

Thanks !
