### ISSUE TITLE
manager: par2 is not installed when Entware is reinstalled

### ISSUE THREAD

**Issue by OneCDOnly** [OneCDOnly/sherpa#142]
Scenario: SAB installed, Par2 uninstalled, need to reinstall Entware.

Entware is reinstalled, but should also be installing Par2 as a dependency of SAB. This is not presently happening.

**Comment by newsat** [comment]
Hi,

I seem to have a similar issue to this where I cannot get SAB working on my qnap. I have tried to reinstall everythign which usually works but Par2 keeps showing as not installed?

![image](https://user-images.githubusercontent.com/77153962/104014339-f80fd280-5206-11eb-8652-cccf438063ac.png)

**Comment by OneCDOnly** [comment]
Hi @newsat can you please post your debug log online?
```
sherpa paste all
```
... then post the URL back here?

**Comment by OneCDOnly** [comment]
@newsat I've just pushed a fix for the failure to install `Par2`.  

But, I'm still curious as to the backtrace shown in your screenshot. I'd still like to see your debug log if that's OK.

**Comment by newsat** [comment]
Sure

 https://termbin.com/fyfa
 
 Thanks for being so responsive

**Comment by OneCDOnly** [comment]
OK, I've had a look though the log. The unusual part is when this error appeared:
```
607	dbug: (LL) * opkg_install_pkg: Checksum or size mismatch for package shine. Either the opkg or the package index are corrupt. Try 'opkg update'.
```
I suspect Entware had a temporary issue there. I'll keep an eye-out for further occurrences. Thanks for reporting this. 👍🏽 

The original failure to install Par2 should now be fixed. If you'd like to try the latest management script, clean your sherpa install with `sherpa clean` first. 

Can you close this issue if everything is OK at your end? 

Cheers!

**Comment by newsat** [comment]
I had this occur after i run sherpa clean and then sherpa reinstall ew
![image](https://user-images.githubusercontent.com/77153962/104080980-c424c380-527f-11eb-8b00-3a472dfb3827.png)
https://termbin.com/o76y

Do I need to download a new file first? Is the par2 qokg supported for me? I was having no issues it seems until about November, since then SAB sickchill dont load up (clicking the link opens to nasname:8081 whereas before it would open to the correct port (example 7073 for sickchill)

**Comment by newsat** [comment]
https://termbin.com/aoq9t

This one may have more info

**Comment by OneCDOnly** [comment]
> Is the par2 qokg supported for me? 

Ah, that's the problem. Your NAS has an ARMv5 arch and there doesn't exist a `Par2` QPKG to-suit. What then happens is **sherpa** should install the `par2cmdline` IPKG via Entware, so you'll still have some ability to repair files. 

What shouldn't happen is that failure to download Par2 (on your NAS, it shouldn't even be tried) so that's something for me to fix. 👍🏽 

> I was having no issues it seems until about November, since then SAB sickchill dont load up (clicking the link opens to nasname:8081 whereas before it would open to the correct port (example 7073 for sickchill)

What does a manual package status check show?

For SABnzbd, use:
```
/etc/init.d/sabnzbd3.sh status
```
... and for SickChill:
```
/etc/init.d/sickchill.sh status
```

**Comment by newsat** [comment]
[~] #
[~] # /etc/init.d/sabnzbd3.sh status
daemon: NOT active
disable QPKG icon: OK
[~] # /etc/init.d/sickchill.sh status
daemon: NOT active
[~] #

**Comment by newsat** [comment]
![image](https://user-images.githubusercontent.com/77153962/104082084-42d12f00-5287-11eb-9f10-4e0e8789e0a2.png)
They both wont start automatically after i did the reinstall

**Comment by OneCDOnly** [comment]
OK, can you please start them via sherpa? 
```
sherpa start sab sc
```

**Comment by newsat** [comment]
note: an upgraded QPKG is available for SickChill
fail: Unable to update cache with 'Par2' (see log for more details)
warn: updated cache with 1 QPKG OK, but 1 QPKG failed
fail: Unable to install 'Par2' (see log for more details)
fail: Installed 1 essential QPKG failed
eror: 'SABnzbd' service failed to start. Check (/var/log/SABnzbd.log) for more information
done: started 2 optional QPKGs OK

**Comment by newsat** [comment]
This is in the sab log

start daemon: >>>>>>>>>> datetime:'Sat Jan  9 14:33:13 EST 2021',request:'start',QPKG:'210107',app:'3.0.2' <<<<<<<<<<
daemon: NOT active
file (/opt/bin/git): exists
update 'SABnzbd' from remote repository: failed!
= ExecuteAndLog()
output: "HEAD is now at feebbb9f Merge branch '3.0.x'
warning: Pulling without specifying how to reconcile divergent branches is
discouraged. You can squelch this message by running one of the following
commands sometime before your next pull:

  git config pull.rebase false  # merge (the default strategy)
  git config pull.rebase true   # rebase
  git config pull.ff only       # fast-forward only

You can replace "git config" with "git config --global" to set a default
preference for all repositories. You can also pass --rebase, --no-rebase,
or --ff-only on the command line to override the configured default per
invocation.

error: The following untracked working tree files would be overwritten by merge:
	.github/workflows/translations.yml
	.tx/config
	po/email/cs.po
	po/main/cs.po
	po/nsis/cs.po
	sabnzbd/deobfuscate_filenames.py
	tests/data/deobfuscate_filenames/E0CcYdGDFbeCAsT3LoID
	tests/data/deobfuscate_filenames/rename.par2
	tests/test_deobfuscate_filenames.py
	tests/test_nzbstuff.py
Please move or remove them before you merge.
Aborting
Updating feebbb9f..e8d6eebb"
result: [1]
current git branch: master
file (/opt/bin/python3): exists
load UI ports from application: OK
start daemon: OK
wait for (/var/run/SABnzbd.pid) to appear: failed!
(/var/run/SABnzbd.pid) not found! (exceeded timeout: 5 seconds)

**Comment by OneCDOnly** [comment]
Hmm, looks like your SABnzbd app has some modified files in it. Suggest cleaning it:
```
/etc/init.d/sabnzbd3.sh clean
```
This will keep your SABnzbd settings, but wipe-out the existing clone, and reclone it from GitHub. 👍🏽 

Also, when you're ready, I've (hopefully) updated **sherpa** to skip the `Par2` package on your model. If you'd like to try it out:
```
sherpa clean
```
... then:
```
sherpa check
```
No-need for a complete Entware reinstall unless it's become corrupt. 😉

**Comment by newsat** [comment]
looks like everything is working for me now thanks!

Couchpotato doesnt work any more for me but I know that hasnt been a part of your install for a long time so all good.

Thanks for your help!

**Comment by OneCDOnly** [comment]
Good work! Thanks for reporting these issues. 👍🏽
