### ISSUE TITLE
SABnzbdplus 2.x conflicting with SABnzbd 3.x, how to uninstall if not detected with cli ?

### ISSUE THREAD

**Issue by tristanbes** [OneCDOnly/sherpa#152]
Hello,

I had an old install of sherpa including SABnzbdplus.
I tried an upgrade (installing the new qpkg), but sherpa cli is not picking the installation of SABnzbdplus.

I tried installing SABnzbd but it fails (I imagine because of the existing installation of the 2.x)

```
[~] # tail -f /var/log/SABnzbd.log
load UI ports from application: OK
start daemon: failed!
= ExecuteAndLog()
output: "Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SABnzbd/SABnzbd/SABnzbd.py", line 40, in <module>
    import feedparser
  File "/opt/lib/python3.9/site-packages/feedparser.py", line 93, in <module>
    _base64decode = getattr(base64, 'decodebytes', base64.decodestring)
AttributeError: module 'base64' has no attribute 'decodestring'"
result: [1]


[~] # sherpa list-installed
Entware
Par2
SABnzbd
nzbToMedia
SickChill
```

What's the procedure to uninstall SABnzbdplus please ? Cannot do it through the UI.
![Capture d’écran 2020-12-05 140522](https://user-images.githubusercontent.com/346010/101243829-1d3e8c00-3703-11eb-925e-a7fb4f952b23.png)

![Capture d’écran 2020-12-05 141522](https://user-images.githubusercontent.com/346010/101244031-5297a980-3704-11eb-946c-194207b5bef0.png)

Thank you.

**Comment by OneCDOnly** [comment]
Hi @tristanbes , the failure to install SAB is a new issue that I only fixed a short while ago. https://github.com/OneCDOnly/sherpa/commit/7dbcd8f23d96e31ff12d8e8e53a3de7cd394bd15

Please try your install of SABnzbd again. 

The new package is called `SABnzbd`. The previous (older) package is called `SABnzbdplus`. 

The new `SABnzbd` package contains an import function to import your settings from the older package into the new one. Please advise if you need help with this.

**Comment by tristanbes** [comment]
ok, thanks i'll try it, but the old is still running, is there a way to uninstall it ?

**Comment by OneCDOnly** [comment]
If you're sure you don't need it (and its configuration anymore), then uninstall it via your App Center.

**Comment by tristanbes** [comment]
the screenshot posted on my previous message shows no option to remove it though (or it's hidden elsewhere ?)

**Comment by OneCDOnly** [comment]
Oh sorry, I didn't notice it was missing. 

Please run this command, then reload your App Center:
```
setcfg SABnzbdplus Status complete -f /etc/config/qpkg.conf
```

**Comment by tristanbes** [comment]
I will when i'll run this command, thank you 👍
