### ISSUE TITLE
Upgrading Sherpa

### ISSUE THREAD

**Issue by dltyih** [OneCDOnly/sherpa#153]
Apologies in advance for a n00b question. I tried searching but did not find an answer (and probably the answer is too obvious that I missed it).

I know I can use "sherpa upgrade all" to upgrade all packages. But when I did a "sherpa status" today, it says sherpa itself is upgradeable. How do I upgrade that? I tried issuing the command "sherpa upgrade all" and "sherpa upgrade sherpa" but received errors.

Many thanks!

[sherpa_201224.qpkg.upgrade.log](https://github.com/OneCDOnly/sherpa/files/5747731/sherpa_201224.qpkg.upgrade.log)

**Comment by dltyih** [comment]
Just struck me that I should install Sherpa as a qpkg ... d'uh

**Comment by OneCDOnly** [comment]
@dltyih as you've installed the **sherpa** QPKG, you also be able to remove the old sherpa.sh script (which is what I guess you were using). For more info: https://github.com/OneCDOnly/sherpa/wiki/For-previous-users
