### ISSUE TITLE
Add Watcher3 to sherpa

### ISSUE THREAD

**Issue by elixdreamer** [OneCDOnly/sherpa#157]
Hello,

Could you please add Watcher3 to sherpa?

https://github.com/barbequesauce/Watcher3
https://forum.qnap.com/viewtopic.php?t=135101

This will help a lot!

Thanks

**Comment by OneCDOnly** [comment]
Watcher3 was installable until the Python3 versions available via Entware progressed and became incompatible with Watcher3. 😞  

As soon as the Watcher3 devs update thier code to work with the later Python3s, I'll be adding Watcher3 back as an installable package.
