### ISSUE TITLE
QSickChill3 installed: how to recover settings from old Synology installation?

### ISSUE THREAD

**Issue by Manfred73** [OneCDOnly/sherpa#158]
Hi,

Recently my Synology broke down. I've now purchased a QNAP and was able to recover the data from the Synology drives.
What I've done so far:

- I've installed a clean version of SickChill3 (via QNAP Club).
- I've also installed QGit 2.21.1 (via QNAP Club).

I can access  SickChill through the web interface, but it's not configured yet.

**Questions:**

1. First of all: Is the package from QNAP Club the right one or is it better to use the sherpa package instead?
2. I didn't install Python on the QNAP and was wondering if this is a requirement, since SickChill seems to be up and running after installation and I can access the web interface. If so, there are different versions (from QNAP itself, but also in the QNAP Club). Which to use?
4. Where do I copy the old data (cache, cache.db, failed.db, sickchill.db, sickchill.db.v44) from the Synology drive to? Should this go to the CONFIG or de var directory?
On Synology everything was under /volume1/@appstore/sickchill/var/data and the config file on Synology was named config.ini.
Looking at the QNAP I see two directories:
- /share/ZFS530_DATA/.qpkg/QSickChill3/CONFIG which contains sickbeard.conf file (looks much like the settings in config.ini from Synology). Can I just copy config.ini and rename it to sickbeard.conf?
- /share/ZFS530_DATA/.qpkg/QSickChill3/var

When I try to update SickChill through the web interface, I see the following error in the log: "Unable to contact github, can't check for update" but when running git from the commandline it can be found.

The settings in sickbeard.conf are:

```
[General]
  git_username = ""
  git_token_password = ""
  git_reset = 1
  branch = ""
  git_remote = origin
  git_remote_url = https://github.com/SickChill/SickChill.git
  cur_commit_hash = ""
  cur_commit_branch = ""
  config_version = 8
```

I have also noticed that when I open SickChill from the QNAP AppStore, it opens on port 30998, while in the sickbeard.conf settings web_port = 8081 which was also the case on the Synology.
This tells me that the sickbeard.conf is not used?

Any help or suggestions to get this working under QNAP would be appreciated.

**Comment by OneCDOnly** [comment]
@Manfred73 sorry, you'll need to contact @QNAP_Stephane for support with his QSickChill package. I've never used it and don't know how it's configured. I also have no access to a Synology NAS and can't advise there either. :(

SickChill is still available via sherpa for-now, but recent commits by the managing dev mean it can't be updated as it breaks SickChill and any other app using Python. The same dev refuses to fix this, so it will be removed as an installable package at some point in the future. 

Try SickGear instead. 😉
