### ISSUE TITLE
sherpa not working?

### ISSUE THREAD

**Issue by greentrancer** [OneCDOnly/sherpa#161]
Hello,

I have just installed sherpa on my QNAP and trying to use PuTTY to install Medusa, etc., however, after I type 'sherpa' and press 'Enter', nothing happens, the screen stay the same.

![putty_2021-10-29_13-40-55](https://user-images.githubusercontent.com/5639078/139436131-89eafbfb-5eaf-44b5-acf8-9289bc9583dc.jpg)

Am I doing something wrong? Thank you.

**Comment by OneCDOnly** [comment]
Hi @greentrancer , you need to exit from the console menu first (type `Q`). 😉

**Comment by greentrancer** [comment]
Of course that I was that silly... Thank you for your help!
