### ISSUE TITLE
packages always autostart after bootup

### ISSUE THREAD

**Issue by slattanzio** [OneCDOnly/sherpa#162]
Hi! I'm not sure if this is a sherpa problem or not but I was hoping that you can help point me in the right direction. 

Installing a package with sherpa works great. Currently, I've installed more that one of the Sickbeard forks but I only use one right now with the others stopped. I do not want to delete the other ones in case I want to switch back. I want to maintain the data. Unfortunately, I notice that when I restart my QNAP device, ALL of the installed sherpa packages restart instead of staying unstarted. I need to manually stop the ones I don't want every time. QNAP specific apps stay in the state they were prior to the reboot. 

I'm wondering if it is expected behaviour or if there is either a QNAP or sherpa setting that I need to set. I appreciate any direction you can give. Sorry if this is the wrong place to ask!

**Comment by OneCDOnly** [comment]
Hey @slattanzio. :)

From memory, stopping a QPKG should also disable it (although, it's been quite a while since I last checked this). Disabling a QPKG should then prevent it starting on QTS bootup. 

Which firmware version is installed on your NAS please?

**Comment by slattanzio** [comment]
Hey @OneCDOnly ! Normally stopping disables it but with anything I install with sherpa, it doesn't. Maybe its an issue with invalid signature apps? Firmware is latest 5.0.0.1853

**Comment by OneCDOnly** [comment]
Ah, yes that's a possibility (and I'm still waiting for QNAP to disclose their super-secret method for signing QPKGs).

I'll need to investigate. Please leave this topic open and I'll post back when I've got something to report. 🤓

**Comment by OneCDOnly** [comment]
Hi @slattanzio I haven't forgotten about this. I've just returned to my QNAP to get a few things up-to-date and I'm checking this out right now...

**Comment by OneCDOnly** [comment]
An update: testing here indicates that packages that were stopped via the app center are not started after NAS bootup. I've been unable to verify the issue. Firmware is also QTS 5.0.0.1858. :(

I'll keep checking this though.

**Comment by slattanzio** [comment]
Hmm...i have the same firmware. I stopped Medusa and Deluge for example and after rebooting, they are started again. I dono how I could have configured it that way if its my fault lol Thanks for continuing to look into it!

**Comment by OneCDOnly** [comment]
No, I don't think you're doing anything wrong - it's just QTS being a QNAP product. 😉 

Interesting observation: I've just started one of my test NAS after having previously stopped all sherpa QPKGs. The NAS booted-up, started each QPKG (including the ones I had stopped), then stopped them again. Weird.

**Comment by an3k** [comment]
Maybe this? https://cheng-yuan-hong.gitbook.io/qdk-qpkg-development-kit/installation-script/generic-installation-script#sys_qpkg_service_enabled

**Comment by OneCDOnly** [comment]
I think I've finally figured out why this happens. Testing now...

**Comment by slattanzio** [comment]
Thanks again for looking into this!

**Comment by OneCDOnly** [comment]
No worries mate, should be fine now.

Although, I just remembered I need to update some of the standalone
packages to behave the same way.

Something for me to do this week. 👍
