### ISSUE TITLE
Sherpa installs onto wrong Volume

### ISSUE THREAD

**Issue by an3k** [OneCDOnly/sherpa#167]
Hi,

I have two Volumes in my QNAP NAS. One is called "System" and runs on two 1 TB M.2 SSDs. As the name suggests everything should be installed and run from there (yay speed). The second Volume is called "Data" and runs on four slow-as-flak 12 TB HDDs. Again, only data should be stored here.

When installing sherpa itself (manual install in the UI) it gets installed onto Data. However, this can be solved my migrating the install to System using the QTS UI. However, even with sherpa on System now every package installed using sherpa is again installed onto Data.
The other problem caused by this is that Entware is not possible to "migrate" onto System.

**Comment by OneCDOnly** [comment]
Hey @an3k :)

Yes, QPKGs are always installed in to the default (system) volume. It's not possible to select where a QPKG will be installed before installing it (blame QNAP for this - they have never provided a UI dialog to choose the target volume). 

If a QPKG was built to support migration, then it can be moved after installation. If not, it can only be installed into the default volume (like Entware). In the specific case of Entware, you could try asking @zyxmon if he wouldn't mind rebuilding the Entware QPKG to support volume migration. The only thing required at the pre-QPKG-build level is that the Entware `qpkg.cfg` will need a line to set the QPKG_VOLUME_SELECT variable like this:
```
# Select volume
# 1: support installation
# 2: support migration
# 3 (1+2): support both installation and migration
QPKG_VOLUME_SELECT="3"
```

**Comment by an3k** [comment]
Hi @OneCDOnly,

Thank you very much for so much information. Back in the day I was creating my own QPKGs and while trying to solve the issue myself I found all the good and ugly bits of the QDK and other stuff again. They were somewhat helpful.
First I checked the scripts (of the Entware qpkg) and noticed QPKG checks where the "Public" share is located and that volume is going to be the installation destination. I thought about pre-setting the variable in question ... but there's an easier way.

`qpkg_cli -P /share/CACHEDEV1_DATA/.qpkg/ -m my.qpkg`

Fun fact: This command does work with Entware (which doesn't support migration) but does not work with SABnzbd (which does support migration).

**Comment by OneCDOnly** [comment]
This is a good hack, but is unsupported by the QTS UI. The inability of QTS to offer a volume for installation is not a fault, it's by-design. 

Maybe when QNAP finally get around to making the QPKG installation processes a little more interactive, I can look at adding this ability to sherpa. 

For now, this is a `can't fix`. 😞
