### ISSUE TITLE
Python3 Modules and LazyLibrarian fail 

### ISSUE THREAD

**Issue by OU812-me2** [OneCDOnly/sherpa#171]
Sherpa Paste isn't working on my QNAP, else I would have supplied the Termbin link.

My issues are as follows:

1. LazyLibrarian has been failing to start since the Python 3.10 update
2. _sherpa check_  - Python Modules Check fails

I force uninstalled Python3 through Opkg and then ran _sherpa check_ but the Python modules check continues to fail repeatedly.
Also tried to get a termbin log link and that too fails. Tried Sherpa Reset and Sherpa clean but no good luck. Also tried backing up and uninstalling LazyLibrarian then reinstalling (basically manual rebuild) without success. Open to suggestions.

`[~] # sherpa check
sherpa 220213 • a mini-package-manager for QNAP NAS

done: installed 3 PIP groups
fail: 'Python3' modules check failed ! result_code: [1]
fail: 'LazyLibrarian' service operation failed. Check (/var/log/LazyLibrarian.log) for more information.
done: restarted 4 dependent QPKGs

[~] # sherpa paste
sherpa 220213 • a mini-package-manager for QNAP NAS

[~] # sherpa clean
done: management script cleaned
[~] # sherpa paste
sherpa 220213 • a mini-package-manager for QNAP NAS`

` 722 dbug: (>>) ParseArguments
    723 dbug: (vv) $USER_ARGS_RAW : 'paste'
    724 dbug: (vv) $_ob_qpkgs_skproc_fl_ : 'true'
    725 dbug: (<<) ParseArguments|0|0|47ms
    726 dbug: (<<) Session.Init|0|0|634ms
    727 dbug: (>>) ArgumentSuggestions
    728 dbug: (<<) ArgumentSuggestions|0|0|15ms
    729 dbug: (II) ----------------------------------------------------------------------------------------------------
    730 dbug: (**)    SCRIPT:          finished: Mon Feb 14 14:14:45 EST 2022
    731 dbug: (**)    SCRIPT:      elapsed time: 00h:00m:01s
    732 dbug: (II) ====================================================================================================`

`    455 dbug: (LL) File "/share/CACHEDEV1_DATA/.qpkg/LazyLibrarian/LazyLibrarian/lazylibrarian/webServe.py", line 77, in <module>
    456 dbug: (LL) from mako import exceptions
    457 dbug: (LL) File "/share/CACHEDEV1_DATA/.qpkg/LazyLibrarian/LazyLibrarian/mako/exceptions.py", line 305, in <module>
    458 dbug: (LL) _install_highlighting()
    459 dbug: (LL) File "/share/CACHEDEV1_DATA/.qpkg/LazyLibrarian/LazyLibrarian/mako/exceptions.py", line 302, in _install_highlighting
    460 dbug: (LL) _install_fallback()
    461 dbug: (LL) File "/share/CACHEDEV1_DATA/.qpkg/LazyLibrarian/LazyLibrarian/mako/exceptions.py", line 290, in _install_fallback
    462 dbug: (LL) from mako.filters import html_escape
    463 dbug: (LL) File "/share/CACHEDEV1_DATA/.qpkg/LazyLibrarian/LazyLibrarian/mako/filters.py", line 42, in <module>
    464 dbug: (LL) html_escape = markupsafe.escape
    465 dbug: (LL) AttributeError: module 'markupsafe' has no attribute 'escape'"
    466 dbug: (LL) result: [1]
    467 dbug: (LL) >>>>>>>>>> datetime:'Fri Feb 11 17:01:40 EST 2022',request:'stopping',QPKG:'220209b',app:'' <<<<<<<<<<
    468 dbug: (LL) daemon: NOT active
    469 dbug: (LL) >>>>>>>>>> datetime:'Fri Feb 11 17:01:41 EST 2022',request:'starting',QPKG:'220209b',app:'' <<<<<<<<<<
    470 dbug: (LL) daemon: NOT active
    471 dbug: (LL) file (/opt/bin/git): exists
    472 dbug: (LL) update 'LazyLibrarian' from remote repository: OK
    473 dbug: (LL) current git branch: master
    474 dbug: (LL) file (/opt/bin/python3): exists
    475 dbug: (LL) load UI ports from application: OK
    476 dbug: (LL) start daemon: failed!
    477 dbug: (LL) = ExecuteAndLog()
    478 dbug: (LL) output: "Traceback (most recent call last):
    479 dbug: (LL) File "/share/CACHEDEV1_DATA/.qpkg/LazyLibrarian/LazyLibrarian/mako/exceptions.py", line 300, in _install_highlighting
    480 dbug: (LL) _install_pygments()
    481 dbug: (LL) File "/share/CACHEDEV1_DATA/.qpkg/LazyLibrarian/LazyLibrarian/mako/exceptions.py", line 284, in _install_pygments
    482 dbug: (LL) from mako.ext.pygmentplugin import syntax_highlight  # noqa
    483 dbug: (LL) File "/share/CACHEDEV1_DATA/.qpkg/LazyLibrarian/LazyLibrarian/mako/ext/pygmentplugin.py", line 7, in <module>
    484 dbug: (LL) from pygments import highlight
    485 dbug: (LL) ModuleNotFoundError: No module named 'pygments'
    486 dbug: (LL)`

`221 dbug: (>>) RunAndLog
    222 dbug: (--) exec: '/opt/bin/python3 -m pip check --no-input' ...
    223 dbug: (LL) adding external log to main log ...
    224 dbug: (LL) ----------------------------------------------------------------------------------------------------
    225 dbug: (LL) = log file: '/share/CACHEDEV1_DATA/.qpkg/sherpa/logs/py3-modules.check.log'
    226 dbug: (LL) = command: '/opt/bin/python3 -m pip check --no-input'
    227 dbug: (LL) ! result_code: [1] ***** stdout/stderr begins below *****
    228 dbug: (LL) pytz-deprecation-shim 0.1.0.post0 requires tzdata, which is not installed.
    229 dbug: (LL) pygithub 1.55 requires deprecated, which is not installed.
    230 dbug: (LL) pygithub 1.55 requires pyjwt, which is not installed.
    231 dbug: (LL) pygithub 1.55 requires pynacl, which is not installed.
    232 dbug: (LL) = ***** stdout/stderr is complete *****
    233 dbug: (LL) ----------------------------------------------------------------------------------------------------
    234 dbug: (<<) RunAndLog|1|0|2,198ms
    235 fail: 'Python3' modules check failed ! result_code: [1].`

[py3-modules.check.log](https://github.com/OneCDOnly/sherpa/files/8063477/py3-modules.check.log)

**Comment by OneCDOnly** [comment]
Looks like you have some major issues there (`paste` not working is a big indicator).

Let's try a reinstall of Entware:
```
sherpa reinstall ew
```

**Comment by OU812-me2** [comment]
@OneCDOnly OMG, you're a genius! That fixed it! Didn't even think of reinstalling Entware. I feel dumb for not having tried it. Thank you!

**Comment by OneCDOnly** [comment]
No worries, reinstalling Entware should really only be used as a last-resort, but I think it was warranted here. 

Cheers! :)

**Comment by OneCDOnly** [comment]
BTW: I've just been checking the dependencies for LazyLibrarian and found it was missing a few. You can install these with:
```
sherpa clean
sherpa check
```
