### ISSUE TITLE
fail: Download & upgrade 3 IPKGs failed [255] when upgrading Medusa or SABnzbd

### ISSUE THREAD

**Issue by mcclown** [OneCDOnly/sherpa#174]
[/share/CACHEDEV1_DATA/.qpkg/SABnzbd/SABnzbd] # sherpa upgrade om
sherpa 220226 • a mini-package-manager for QNAP NAS

done: package cache updated with 1 QPKG
fail: Download & upgrade 3 IPKGs failed [255]

**Comment by OneCDOnly** [comment]
Hi, can you please post your sherpa log online:
```
sherpa paste log
```
... then post the URL back here? This will give me something to investigate.

**Comment by mcclown** [comment]
Here you go: https://termbin.com/wxq1

The upgrades seem to work despite the IPKG errors

**Comment by OneCDOnly** [comment]
Thank you for posting your log. 👍🏽 

Looks like your Python version is out-of-date. This means it will need upgrading, along with all installed Python modules. 

This can be fixed with:
```
sherpa check
```

**Comment by mcclown** [comment]
Hi, I tried that and I'm just getting more errors

https://termbin.com/i1ao

**Comment by mcclown** [comment]
Running "opkg update", then "sherpa check" seems to have done the trick

**Comment by OneCDOnly** [comment]
Good work.

I think I'll force an `opkg update` whenever running a `sherpa check` to prevent this issue occurring again. 

The default is to only update opkg no more than once-per-hour to reduce load on the Entware servers. But, in this case, I think a forced update is warranted. 

Thanks for reporting this. 👍🏽

**Comment by mcclown** [comment]
After all that I'm still having an issue with SABnzbad with the following error. I'll keep digging and open another issue if I can't figure it out

SABYenc disabled: no correct version found! (Found v5.0.1, expecting v4.0.0)
