### ISSUE TITLE
GIT error when updating packages (OSickGear, SABnzbd)

### ISSUE THREAD

**Issue by ouija** [OneCDOnly/sherpa#175]
Noticed this occurred today when restarting some packages like OSickGear, SABnzbd, etc:
`fatal: remote error:
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information."
`

I would assume this is occurring because the various packages are using `http` and not `https` in relation to the [github] source URLs.

Will reply with follow up once I've investigated further, just wanted to put this on your radar.

**Comment by OneCDOnly** [comment]
Oops. Didn't know about this. 

Thank you for the link (very informative) and the solution. Works well here. I'll update all sherpa packages that pull from source right now.

**Comment by OneCDOnly** [comment]
**Update:** looks like only `Omedusa`, `OSickGear` and `SABnzbd` QPKGs are affected by this. The rest use HTTPS. 

Which is another black-mark for me, as all packages should have used the same protocol, not a mixture. :grin:
