### ISSUE TITLE
With firmware 5.01.2034, some applications no longer work.

### ISSUE THREAD

**Issue by Fantomas68** [OneCDOnly/sherpa#194]
The following apps no longer work:
LazyLibrarian
nzbToMedia
Par2

**Comment by OneCDOnly** [comment]
`Par2` should now be fixed, as @QNAP_Stephane just released new versions, which I've updated in sherpa. 

The other two are news to me. What isn't working? Any errors shown?

**Comment by saropa-zz** [comment]
even worse for me.. after installing new firmware, sherpa did not work anymore.
removed, and tried re-install, but i am getting error : _[App Center] Failed to install sherpa (CLI). Downgrade QTS to 5.0.0 or an older compatible version.

**Comment by OneCDOnly** [comment]
@saropa-zz you'll need to re-enable unsigned packages in your App Center. This is a new requirement with QTS 5.0.1.

**Comment by OneCDOnly** [comment]
@Fantomas68 are your apps working now? Have you made any progress?

**Comment by OneCDOnly** [comment]
Unconfirmed, no response from OP.
