### ISSUE TITLE
QTS 5.0.1.2145 - Par2cmdLine

### ISSUE THREAD

**Issue by netopir** [OneCDOnly/sherpa#213]
Hello

After update to QTS 5.0.1.2145  the Par2cmdLine don't want to start enymore.

Here is the link for debug details: https://termbin.com/w74x

Regrads

**Comment by OneCDOnly** [comment]
Hi @netopir :)

What is your Par2 package version please? This should be visible in your QTS App Center.

**Comment by netopir** [comment]
Par2cmdLine (CLI) v0.8.1.1 (Instalation Date 2022/06/14)

**Comment by OneCDOnly** [comment]
Did you re-check the tickbox in your App Center to allow unsigned packages again? It's automatically disabled after updating to QTS 5.0.1. 

Can you then try starting Par2 manually?
```
/etc/init.d/Par2.sh start
```
... then check that it has started:
```
file /usr/bin/par2
```

**Comment by netopir** [comment]
Hello

Allow installation of applications without a valid digital signature are checked.

[~] # /etc/init.d/Par2.sh start
Par2 is disabled.

**Comment by OneCDOnly** [comment]
Ah, it's disabled. No problem:
```
sherpa start par2
```
... then please check the `par2` binary is available:
```
file /usr/bin/par2
```

**Comment by netopir** [comment]
Hello

[~] # file /usr/bin/par2
/usr/bin/par2: symbolic link to /share/CACHEDEV1_DATA/.qpkg/Par2/bin/par2

THX that slow the problen, now i know for the next time.

Regrads
