### ISSUE TITLE
bort: A required NAS system file is missing (/bin/less): aborting ...

### ISSUE THREAD

**Issue by AGMuc** [OneCDOnly/sherpa#240]
Hello!

After a reinstallation of Sherpa I get the following error at startup 

$ sudo sherpa
bort: A required NAS system file is missing (/bin/less): aborting ...

Regrads

**Comment by OneCDOnly** [comment]
Hi @AGMuc, and thanks for reporting this. 👍🏽 

Oops, I forgot `less` isn't always available in QTS. I think it depends on which firmware version is installed. I'll fix this now. 

For the record, what is your NAS model and QTS version (and build number) please?

**Comment by AGMuc** [comment]
Thank you! Its a TS-231P with QTS 5.0.1.2248 Build 20221215

**Comment by OneCDOnly** [comment]
Cheers mate. 😄 

I’ve pushed a fix for this issue. Please reset your sherpa install, then you should be good to run sherpa as usual.
