### ISSUE TITLE
Startup failed NZBGet and SABnzbd

### ISSUE THREAD

**Issue by AGMuc** [OneCDOnly/sherpa#249]
Hello,
I can't start either NZBget or Sabnzbd, the following message comes in the terminal:

proc: calculation of IPK dependencies ... /share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 2096: IPKGs.AcToDownload.Add: command not found

And in the NAS:

Error --- --- localhost --- --- [NZBGet] /opt/bin/nzbget not found! (Timeout exceeded: 30 seconds)

Error -- --- localhost --- --- [SABnzbd] failed!

When I try to open the IP, as expected, only ERR_CONNECTION_REFUSED comes up.

Thanks a lot!

NAS: TS-231P with QTS 5.0.1.2248 Build 20221215

Many greetings

**Comment by OneCDOnly** [comment]
Oops, I'm on it...

**Comment by OneCDOnly** [comment]
OK, should be fine now. 

Please run a `sherpa reset` to ensure you're using the latest management script. 

Thanks for reporting this. 👍🏽

**Comment by AGMuc** [comment]
Works perfectly, thanks mate!
