### ISSUE TITLE
Error: create new virtual Python environment: failed!

### ISSUE THREAD

**Issue by ouija** [OneCDOnly/sherpa#260]
Hey,

Recently ran the `sherpa upgrade all` and none of my packages (SABnzbd, OSickGear)  are working anymore, where I'm getting the following error when running the individual scripts for each package:

```
./sabnzbd3.sh restart
daemon active: false
auto-update: true
file /opt/bin/git: exists
update 'SABnzbd' from remote repository: OK
current git branch: master
create new virtual Python environment: failed!
unable to install addons: virtual environment does not exist!
```

**Comment by ouija** [comment]
**UPDATE:**  It seems I've managed to resolve this issue by simply running the `sherpa check` command, which appears to have fixed the issue:

```
sherpa check
sherpa 230201-beta • a mini-package-manager for QNAP NAS

done: installed 1 addon PIP
done: restarted 1 dependent QPKG
done: check OK

* These package actions completed OK:
        restart SABnzbd in 00m:45s
```

Just wanted to make note of this and close the issue.   Thanks!

**Comment by OneCDOnly** [comment]
Good work mate! 👍🏽 

Can you please let me know if this happens again? Cheers.

**Comment by OneCDOnly** [comment]
Also, the service script log should show what happened when it was checking for the `venv` for SABnzbd. 

You can view this with `/etc/init.d/sabnzbd3.sh log`
