### ISSUE TITLE
QuTS hero: running sherpa as admin user

### ISSUE THREAD

**Issue by Jonnaz** [OneCDOnly/sherpa#261]
I am using version QuTShero h5.0.1.1148 with sherpa version 230206-beta

logged in using ssh with the admin user and running any basic sherpa command ie:

`sherpa check`

I get the following output:

```
sherpa 230206-beta • a mini-package-manager for QNAP NAS

proc: environment/share/ZFS2_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 377: SUDO_USER: unbound variable
```

If I prepend the command with `sudo` then it works as expected.

I do wonder that it is a bit more of a PEBKAC issue, however it worked fine (without the need for `sudo`)the last time I ran updates a few weeks ago.

**Comment by OneCDOnly** [comment]
Hello. :)

No, this was my fault. It's now fixed. Please run `sherpa reset` to get the updated management script.

**Comment by Jonnaz** [comment]
Hey @OneCDOnly 

I can confirm it is sorted 👍🏻
