### ISSUE TITLE
`nzbToMedia` infinite loop when restoring configuration

### ISSUE THREAD

**Issue by rivy** [OneCDOnly/sherpa#266]
Hey again, 👋🏻 
I ran into another issue.
I noticed that my upgraded nzbToMedia stopped working (with incorrect configuration).
It looks like it is using the default configuration.

And then, when restoring with `sherpa restore nzbtomedia`, `sherpa` hangs...

```shell
$ sherpa 230309-stable • a mini-package-manager for QNAP NAS

proc: restoring dependent QPKG: 50% (0/1): 1 in-progress
```

Using `nzbtomedia.sh` directly shows an infinite loop while restoring...

```shell
$ ./nzbtomedia.sh --restore
scripts_path_source: SABnzbd 'script_dir'
scripts_path: /share/Download/nzbToMedia
stop package: OK
package active: false
restore configuration backup: OK
auto-update: true
file /opt/bin/git: exists
current git branch: master, new git branch: master
update configuration backup: OK
new git branch has been specified, so clean local repository: OK
clone 'nzbToMedia' from remote repository: OK
current git branch: master
stop package: OK
package active: false
restore configuration backup: OK
auto-update: true
file /opt/bin/git: exists
current git branch: master, new git branch: master
update configuration backup: OK
new git branch has been specified, so clean local repository: OK
clone 'nzbToMedia' from remote repository: OK
current git branch: master
stop package: OK
package active: false
restore configuration backup: OK
auto-update: true
file /opt/bin/git: exists
current git branch: master, new git branch: master
update configuration backup: OK
new git branch has been specified, so clean local repository: OK
clone 'nzbToMedia' from remote repository: OK
current git branch: master
stop package: OK
package active: false
restore configuration backup: OK
auto-update: true
...
```

I tried resets, reinstalls, and a full uninstall/install.

Sherpa/QPKG info is...

```shell
$ sherpa version
QPKG: 230227
manager: 230309-stable
loader: 230227
objects: 230309
packages: 230309
$ sherpa status
sherpa status
sherpa 230309-stable • a mini-package-manager for QNAP NAS

note: an updated QPKG is available for HideThatBanner

• standalone QPKGs:     • QPKG statuses (last result):     • QPKG version (new):  • installation path:
   duf                   - enabled, started (OK)            220809                 /share/CACHEDEV1_DATA/.qpkg/duf
   Entware               - enabled, started (N/A)           1.03a                  /share/CACHEDEV1_DATA/.qpkg/Entware
   HideThatBanner        - enabled, started (OK)            230214 (230309)        /share/CACHEDEV1_DATA/.qpkg/HideThatBanner
   Par2                  - enabled, started (N/A)           0.8.1.1                /share/CACHEDEV1_DATA/.qpkg/Par2
   QDK                   - not installed                    2.3.13
   RunLast               - enabled, started (OK)            230224                 /share/CACHEDEV1_DATA/.qpkg/RunLast
   sha3sum               - enabled, started (N/A)           221205                 /share/CACHEDEV1_DATA/.qpkg/sha3sum
   sherpa                - enabled, started (OK)            230227                 /share/CACHEDEV1_DATA/.qpkg/sherpa
   SortMyQPKGs           - not installed                    230227

• dependent QPKGs:      • QPKG statuses (last result):     • QPKG version (new):  • installation path:
   ClamAV                - not installed                    230215
   Deluge-server         - not installed                    230215
   Deluge-web            - not installed                    230228
   Headphones            - not installed                    230215
   inxi                  - enabled, started (OK)            230305                 /share/CACHEDEV1_DATA/.qpkg/inxi
   LazyLibrarian         - enabled, started (OK)            230214                 /share/CACHEDEV1_DATA/.qpkg/LazyLibrarian
   OMedusa               - enabled, started (OK)            230213                 /share/CACHEDEV1_DATA/.qpkg/OMedusa
   Mylar3                - not installed                    230214
   NZBGet                - enabled, started (OK)            230215                 /share/CACHEDEV1_DATA/.qpkg/NZBGet
   NZBHydra2             - not installed                    230213
   nzbToMedia            - enabled, started (OK)            230214                 /share/CACHEDEV1_DATA/.qpkg/nzbToMedia
   pyLoad                - not installed                    230302c
   OqBittorrent          - not installed                    230225a
   SABnzbd               - enabled, started (OK)            230301                 /share/CACHEDEV1_DATA/.qpkg/SABnzbd
   OSickGear             - enabled, started (OK)            230214                 /share/CACHEDEV1_DATA/.qpkg/OSickGear
   OTransmission         - not installed                    230214
   OWatcher3             - not installed                    230213
```

**Comment by OneCDOnly** [comment]
Hey Roy. :)

Hmm, that's a new one.

I'm investigating now...

**Comment by OneCDOnly** [comment]
It's odd that it thinks the source branch has changed. 

I wonder if your nzbToMedia setup has been configured to self-update?

Can you please check your `autoProcessMedia.cfg` file as follows?
```
head -n20 $(getcfg nzbToMedia Install_Path -f /etc/config/qpkg.conf)/repo-cache/autoProcessMedia.cfg
```
Can you please paste the output back here?

**Comment by rivy** [comment]
No rush.
I copied the old config directly into the `repo-cache` directory and `nzbToMedia` is working fine.
I just suspect that upon next restart or upgrade, I'll have to manually copy the configuration back into the `repo-cache` directory.

**Comment by OneCDOnly** [comment]
> No rush. I copied the old config directly into the `repo-cache` directory and `nzbToMedia` is working fine. I just suspect that upon next restart or upgrade, I'll have to manually copy the configuration back into the `repo-cache` directory.

Ah, that's interesting. The service script should do that for you (it's unfortunate Clinton Hall decided to keep the application configs within the application installation directory), but maybe it's broken.

**Comment by OneCDOnly** [comment]
Also, can you please check the git branch config within `repo-cache`?
```
cd $(getcfg nzbToMedia Install_Path -f /etc/config/qpkg.conf)/repo-cache
git branch -a
```

**Comment by OneCDOnly** [comment]
~Just thinking out-loud here, but maybe we could store `autoProcessMedia.cfg` in a separate `config` directory (as nearly all other QPKGs do), and create a symlink in the application root (i.e. `repo-cache`) to it?~

~This would prevent the tedious backup-and-restore process that presently takes place. Whenever the `repo-cache` is cleaned (on git branch change), it would only be necessary to recreate the symlink via the service script.~

**Comment by rivy** [comment]
> Can you please check your autoProcessMedia.cfg file as follows?
> ```
> head -n20 $(getcfg nzbToMedia Install_Path -f /etc/config/qpkg.conf)/repo-cache/autoProcessMedia.cfg
> ```

```shell
$ head -n20 $(getcfg nzbToMedia Install_Path -f /etc/config/qpkg.conf)/repo-cache/autoProcessMedia.cfg
# nzbToMedia Configuration
# For more information, visit https://github.com/clinton-hall/nzbToMedia/wiki

[General]
    # Enable/Disable update notifications
    version_notify = 1
    # Enable/Disable automatic updates
    auto_update = 0
    # Set to the full path to the git executable
    git_path = ""
    # GitHUB user for repo
    git_user = ""
    # GitHUB branch for repo
    git_branch = ""
    # Enable/Disable forceful cleaning of leftover files following postprocess
    force_clean = 0
    # Enable/Disable logging debug messages to nzbtomedia.log
    log_debug = 0
    # Enable/Disable logging database messages to nzbtomedia.log
    log_db = 0
```

> Also, can you please check the git branch config within `repo-cache`?
> 
> ```
> cd $(getcfg nzbToMedia Install_Path -f /etc/config/qpkg.conf)/repo-cache
> git branch -a
> ```

```shell
$ cd $(getcfg nzbToMedia Install_Path -f /etc/config/qpkg.conf)/repo-cache
$ git branch -a
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/master
```

**Comment by OneCDOnly** [comment]
Cheers mate, all those look fine. 👍🏽 

I don't know why you're getting that loop. Looking at the code, I can almost picture a loop forming, but I can't make it happen in my tests. 

~I think I'll work on doing the symlink thing into `repo-cache` instead. That should help keep everyone's `autoProcessMedia.cfg` safe, and means I can get rid of the backup/restore part of updating the application from GitHub.~ 

I'll post back when I've got a new nzbToMedia QPKG ready for you. Thanks for reporting this.

**Comment by OneCDOnly** [comment]
I've then remembered we can't use a symlink to the config, as it's far too-easy for a symlink to be overwritten when editing the linked file. :(

So, I'm back to diagnosing the existing setup... I'll keep working on it.

**Comment by OneCDOnly** [comment]
OK, there's a new nzbToMedia QPKG available: 230309

To get it right now, please run:
```
sherpa reset; sherpa upgrade nzbtom
```
Please let me know how it goes. :)

**Comment by rivy** [comment]
👍🏻 
Looks good!
No hangs or loops, and correct configuration is restored.
Thanks!

**Comment by OneCDOnly** [comment]
Thanks again Roy. Appreciate you reporting these issues. 👍🏽 

Please reopen this issue if it happens again.
