### ISSUE TITLE
openssl issues with OPKG update

### ISSUE THREAD

**Issue by ouija** [OneCDOnly/sherpa#269]
Hey,

This _might_ be tied to your issue posted from yesterday, but I recently did my monthly update of my QNAP and OPKG and sherpa packages, and now I'm having issues with openssl and git not working, because openssl apparently has updated to v3 but git (or git-http) requires openssl 1.1 and git will now throw the error:

`/opt/lib/git-core/git-remote-https: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

And sherpa will throw errors as well, because the repos fail to update when running the scripts, and throw the error: `update 'OSickGear' from remote repository: failed!`

Not quite sure how to address this properly, but packages are still functional for now, but openssl and GIT and package updates aren't working for the time being...

**Comment by OneCDOnly** [comment]
Sounds related to this: https://github.com/Entware/Entware/issues/913

After reinstalling Entware, I've had no trouble. 👍🏽 

Can you please try this? 
```
sherpa reinstall ew
```

**Comment by ouija** [comment]
You, sir, are **brilliant!**  Running `sherpa reinstall ew` to reinstall Entware _(and all installed opkg packages)_ did the trick!  Thanks again for such great support my friend.

**Comment by OneCDOnly** [comment]
Cheers mate. :)
