### ISSUE TITLE
SABnzbd enabled, inanctive after upgrade to QTS 5.0.1.2376 build 20230421

### ISSUE THREAD

**Issue by jbelvoncik** [OneCDOnly/sherpa#270]
111 ABnzbd.py --daemon --browser 0 --config-file /share/CACHEDEV1_DATA/.qpkg/SABnzbd/config/config.ini --pidfile /var/run/SABnzbd.pid'
    112 dbug: (LL) ! result_code: [1] ***** stdout/stderr begins below *****
    113 dbug: (LL) Not all required Python modules are available, please check requirements.txt
    114 dbug: (LL) Missing module: sabctools.sabctools
    115 dbug: (LL) You can read more at: https://sabnzbd.org/wiki/installation/install-off-modules
    116 dbug: (LL) If you still experience problems, remove all .pyc files in this folder and subfolders
    117 dbug: (LL) = ***** stdout/stderr is complete *****
    118 dbug: (LL) ----------------------------------------------------------------------------------------------------
    119 failed!
    120 >>>>>>>>>> datetime:'Tue May  2 22:56:15 CEST 2023', request:'stopping', package:'230503', service:'230503', app:'4.0.1' <<<<<<<<<<
    121 daemon active: false
    122 >>>>>>>>>> datetime:'Tue May  2 22:56:23 CEST 2023', request:'starting', package:'230503', service:'230503', app:'4.0.1' <<<<<<<<<<
    123 daemon active: false
    124 auto-update: true
    125 file /opt/bin/git: exists
    126 update 'SABnzbd' from remote repository: OK
    127 active git branch: 'master'
    128 KLUDGE: exclude various PyPI modules from installation: OK
    129 install 'requirements' PyPI modules: OK
    130 file /opt/bin/python3: exists
    131 load ports from configuration file: OK
    132 start daemon: dbug: (LL) adding external log to main log ...
    133 dbug: (LL) ----------------------------------------------------------------------------------------------------
    134 dbug: (LL) = log file: '/var/log/DisplayRunAndLog_8Y9sfF'
    135 dbug: (LL) command: '. /share/CACHEDEV1_DATA/.qpkg/SABnzbd/venv/bin/activate && cd /share/CACHEDEV1_DATA/.qpkg/SABnzbd/repo-cache && /share/CACHEDEV1_DATA/.qpkg/SABnzbd/venv/bin/python3 /share/CACHEDEV1_DATA/.qpkg/SABnzbd/repo-cache/S    135 ABnzbd.py --daemon --browser 0 --config-file /share/CACHEDEV1_DATA/.qpkg/SABnzbd/config/config.ini --pidfile /var/run/SABnzbd.pid'
    136 dbug: (LL) ! result_code: [1] ***** stdout/stderr begins below *****
    137 dbug: (LL) Not all required Python modules are available, please check requirements.txt
    138 dbug: (LL) Missing module: sabctools.sabctools
    139 dbug: (LL) You can read more at: https://sabnzbd.org/wiki/installation/install-off-modules
    140 dbug: (LL) If you still experience problems, remove all .pyc files in this folder and subfolders
    141 dbug: (LL) = ***** stdout/stderr is complete *****
    142 dbug: (LL) ----------------------------------------------------------------------------------------------------
    143 failed!
    144 >>>>>>>>>> datetime:'Tue May  2 22:58:25 CEST 2023', request:'stopping', package:'230503', service:'230503', app:'4.0.1' <<<<<<<<<<
    145 daemon active: false
    146 >>>>>>>>>> datetime:'Tue May  2 22:58:26 CEST 2023', request:'starting', package:'230503', service:'230503', app:'4.0.1' <<<<<<<<<<
    147 daemon active: false
    148 auto-update: true
    149 file /opt/bin/git: exists
    150 update 'SABnzbd' from remote repository: OK
    151 active git branch: 'master'
    152 KLUDGE: exclude various PyPI modules from installation: OK
    153 install 'requirements' PyPI modules: OK
    154 file /opt/bin/python3: exists
    155 load ports from configuration file: OK
    156 start daemon: dbug: (LL) adding external log to main log ...
    157 dbug: (LL) ----------------------------------------------------------------------------------------------------
    158 dbug: (LL) = log file: '/var/log/DisplayRunAndLog_RybUrN'
    159 dbug: (LL) command: '. /share/CACHEDEV1_DATA/.qpkg/SABnzbd/venv/bin/activate && cd /share/CACHEDEV1_DATA/.qpkg/SABnzbd/repo-cache && /share/CACHEDEV1_DATA/.qpkg/SABnzbd/venv/bin/python3 /share/CACHEDEV1_DATA/.qpkg/SABnzbd/repo-cache/S    159 ABnzbd.py --daemon --browser 0 --config-file /share/CACHEDEV1_DATA/.qpkg/SABnzbd/config/config.ini --pidfile /var/run/SABnzbd.pid'
    160 dbug: (LL) ! result_code: [1] ***** stdout/stderr begins below *****
    161 dbug: (LL) Not all required Python modules are available, please check requirements.txt
    162 dbug: (LL) Missing module: sabctools.sabctools
    163 dbug: (LL) You can read more at: https://sabnzbd.org/wiki/installation/install-off-modules
    164 dbug: (LL) If you still experience problems, remove all .pyc files in this folder and subfolders
    165 dbug: (LL) = ***** stdout/stderr is complete *****
    166 dbug: (LL) ----------------------------------------------------------------------------------------------------
    167 failed!

**Comment by OneCDOnly** [comment]
Hi Jozef. :)

Can you please `clean` your SABnzbd installation? 
```
sherpa clean sab
```

**Comment by jbelvoncik** [comment]
Hi, 
thank you for your effort, 
I did and doesn't work yet

[Bug_SABnzbd.txt](https://github.com/OneCDOnly/sherpa/files/11379393/Bug_SABnzbd.txt)

**Comment by jbelvoncik** [comment]
Even pyload doesn't work. 
I did clean.

**Comment by OneCDOnly** [comment]
Can you please now reinstall your Entware QPKG? 
```
sherpa reinstall ew
```

**Comment by sboehle** [comment]
I had also issues after upgrading my qnap yesterday. The following solved my issues:

sherpa upgrade all
sherpa check

**Comment by jbelvoncik** [comment]
Thank you, working.
Thank you for all your efforts. 
I really appreciate sherpa's distribution.
All the best.

**Comment by arakasi55** [comment]
> I had also issues after upgrading my qnap yesterday. The following solved my issues:
> 
> sherpa upgrade all sherpa check

Thanks - this also resolved the issue for me
