### ISSUE TITLE
SABnzbd            - enabled, inactive      230604

### ISSUE THREAD

**Issue by jbelvoncik** [OneCDOnly/sherpa#272]
Hi,
I did upgrade SABnzbd and is inactive:

1. I did sherpa uninstall sb
2. I did sherpa clean all
3. I did sherpa check all
4. I did reboot system
5. I did sherpa install sb
SABnzbd            - enabled, inactive      230604 

What should I do pls?

**Comment by DynaMight1124** [comment]
Yeah I have the same issue too. SAB working fine, upgraded to 230604 and SAB stopped. Tried clean, check, reinstall plus the usual restart but not worked.

**Comment by OneCDOnly** [comment]
Hi guys, can you please reinstall Entware?
```
sherpa reinstall ew
```

**Comment by jbelvoncik** [comment]
Thank youuuuuuuuuuu, works

**Comment by OneCDOnly** [comment]
I've just pushed an update that will cause Entware to be auto-reinstalled if it was installed prior to the most recent IPK updates. This should mean users won't need to manually reinstall Entware.
