### ISSUE TITLE
Entware Doesn't Re-Install Packages

### ISSUE THREAD

**Issue by firstkevinds** [OneCDOnly/sherpa#273]
sherpa reinstalls Entware but it doesn't reinstall the packages that were installed before.

Is it possible to record these so that when Entraware is reinstalled that it will reinstall the packages we installed, not just those used by sherpa?

**Comment by OneCDOnly** [comment]
Hey @online-stuff. 

Yes, this is by-design. The list of Entware packages that were installed is recorded in the cache path for sherpa. You can view this file with:
```
cat $(getcfg sherpa install_path -f /etc/config/qpkg.conf)/cache/ipk.prev.list
```

However, I've been thinking about changing this to reinstall all IPKs that were installed previously. I'll add this to my todo list and keep this issue open until the changes are made.
