### ISSUE TITLE
unable to install sherpa on QTS 5.1.1.2491 (2023/08/15)

### ISSUE THREAD

**Issue by grijzeduifnl** [OneCDOnly/sherpa#275]
Hi OneCDOnly, 

I have sherpa running on my old NAS TS-659 QTS 20230621-4.2.6, works great.
Bought myself replacement, TS-453E QTS 5.1.1.2491 (2023/08/15) and want to install sherpa here as well.

Checked app-center: Allow installation of applications without a valid digital signature
Downloaded the latest sherpa QPKG - sherpa_230825

But get the following error:
Error	2023-08-30	17:01:44	---	---	Web Desktop	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0	App Center	App Installation	[App Center] Failed to install sherpa_230825.qpkg due to a file format error.

Any idea about the cause?

**Comment by OneCDOnly** [comment]
Hi, and thanks for reporting this issue. 👍🏽 

hmm... can you please generate an MD5 checksum on the file you've downloaded and compare it against the original? 

The original file is 88,878 bytes, and the checksum is: `9e0bbb9e2bb3659ff36d31f23dfefe6a` as shown here: https://github.com/OneCDOnly/sherpa/blob/stable/QPKGs/sherpa/build/sherpa_230825.qpkg.md5

**Comment by grijzeduifnl** [comment]
Get-FileHash .\sherpa_230825.qpkg -Algorithm MD5

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
MD5             9E0BBB9E2BB3659FF36D31F23DFEFE6A                                       C:\Users\phili\Downloads\sherpa_230825.qpkg

looks fine to me

**Comment by OneCDOnly** [comment]
Yup, looks correct. 

That means something may be going wrong when it's being uploaded through your browser into the QTS App Center UI.

Can you try installing it at the CLI instead? This allows us to bypass any browser shenanigans.  If you copy it to your Public share on the NAS, then SSH into that NAS, you can install it with: `sh /share/Public/sherpa_230825.qpkg`

**Comment by grijzeduifnl** [comment]
somewhat better:
[locadmin@TS-453E /]$ sh /share/Public/sherpa_230825.qpkg
Install QNAP package on TS-NAS...
./
./qinstall.sh
./qpkg.cfg
./package_routines
./built_info
2+1 records in
2+1 records out
65089 bytes (63.6KB) copied, 0.000060 seconds, 1.0GB/s
63+1 records in
63+1 records out
65089 bytes (63.6KB) copied, 0.000226 seconds, 274.7MB/s
Firmware check is fine.
Link service start/stop script: sherpa-service.sh
ln: /etc/init.d/sherpa-service.sh: Permission denied
Set QPKG information in /etc/config/qpkg.conf
mkdir: can't create directory '/logs': Permission denied
touch: /logs/session.archive.log: No such file or directory
package_routines: line 117: /logs/session.archive.log: No such file or directory

##########################################################

[locadmin@TS-453E /]$ sudo sh /share/Public/sherpa_230825.qpkg
Install QNAP package on TS-NAS...
./
./qinstall.sh
./qpkg.cfg
./package_routines
./built_info
2+1 records in
2+1 records out
65089 bytes (63.6KB) copied, 0.000041 seconds, 1.5GB/s
63+1 records in
63+1 records out
65089 bytes (63.6KB) copied, 0.000216 seconds, 287.4MB/s
sherpa  is already installed. Setup will now perform package upgrading.
Firmware check is fine.
Link service start/stop script: sherpa-service.sh
Set QPKG information in /etc/config/qpkg.conf
symlinks created

I think this looks much better.

In App Center Sherpa look installed, just with an exclamation mark "There is no digital signature"
I will continue installation from here, thanxs for the help!

**Comment by OneCDOnly** [comment]
Good work mate. 👍🏽 

Yes, when you run various sherpa actions (like `install`, `check`, etc...), that will make sherpa "sign" itself, and any other QPKGs installed through it. It needs the `sqlite3-cli` package from Entware to do this, so signing isn't possible until Entware has been installed. :) 

Now that I think of it, I wonder if QTS has its own version of `sqlite` hidden away somewhere? I should try searching for it.

**Comment by grijzeduifnl** [comment]
I'll give it a try, TY

**Comment by grijzeduifnl** [comment]
can I use this version that is already installed?

[locadmin@TS-453E /]$ sudo find -name sqlite3
Password:
./share/CACHEDEV1_DATA/.qpkg/HybridBackup/CloudConnector3/bin/sqlite3
./share/CACHEDEV1_DATA/.qpkg/HybridBackup/CloudConnector3/python/lib/python3.11/sqlite3
./share/CACHEDEV1_DATA/.qpkg/CacheMount/python/lib/python3.7/sqlite3
./share/CACHEDEV1_DATA/.qpkg/CacheMount/bin/sqlite3
./mnt/ext/opt/netmgr/api/lib/django/db/backends/sqlite3
./mnt/ext/opt/Python/lib/python2.7/sqlite3
[locadmin@TS-453E /]$

**Comment by grijzeduifnl** [comment]
Everything (SABNZBD) up & running

**Comment by OneCDOnly** [comment]
Awesome! 

Thanks for finding those other `sqlite` binaries... I'll do some testing and see if they respond the same way as the Entware one. If they do, then I can add them as alternatives. 👍🏽

**Comment by OneCDOnly** [comment]
**update:** I've [added](https://github.com/OneCDOnly/sherpa/commit/24618d5c0c56d29aab311f5352a37855fad64a14) a couple of those locations to sherpa, so package signing can be done without Entware, as-long as one of those is available. 

Cheers mate. 👍🏽

**Comment by grijzeduifnl** [comment]
Thanks, and keep up the good work!
