### ISSUE TITLE
Invalid file format

### ISSUE THREAD

**Issue by d9001089** [OneCDOnly/sherpa#276]
Hello, I have a QNAP TVS 471 and I have been running your package for years but when I tried to uninstall and reinstall your latest package I get the following. 

Failed to install Sherpa_xxx.qpkg due to a file format error.  Any idea what is going on? 

![image](https://github.com/OneCDOnly/sherpa/assets/17131678/c4735f76-2fd4-40b4-b1c1-398690cb2e8e)

![Capture](https://github.com/OneCDOnly/sherpa/assets/17131678/7e923ce4-d167-4bdc-88c6-8e126a76e389)

**Comment by OneCDOnly** [comment]
Hi, and thanks for reporting this issue. 

What version of QTS is installed on your NAS please? 

I've had a few reports lately that the QTS App Center UI throws an error when the user attempts to manually install a QPKG. Installation works fine at the CLI though. I don't know the reason for it: the QPKGs are perfectly valid. I suspect there's a new QTS bug waiting to be fixed.  

Anyway, please try installing the QPKG at the CLI. Copy the QPKG to your `Public` NAS share, then install it with:
```
sudo sh sherpa_230825.qpkg
```

**Comment by d9001089** [comment]
here are the specs...
![image](https://github.com/OneCDOnly/sherpa/assets/17131678/de310bb7-5486-4ace-9bee-520d168e3e69)

**Comment by d9001089** [comment]
installing it from the CLI worked.... thanks for the workaround

**Comment by OneCDOnly** [comment]
Excellent. :)

If you have any further problems, please feel free to reopen this issue.
