### ISSUE TITLE
Entware install problem?

### ISSUE THREAD

**Issue by mvught** [OneCDOnly/sherpa#284]
Is there a problem with Entware? im getting this after all the commands: 

[~] # sherpa status && sherpa check && sherpa upgrade all
sherpa v240212-stable

done: processing complete.

• QPKG name:         • QPKG statuses:       • QPKG version:  • App version:  • QPKG installation path:                       
   ClamAV             - enabled, inactive      240211           0.104.4         /share/MD0_DATA/.qpkg/ClamAV                 
   Deluge-server      - not installed          240205           2.1.1        
   Deluge-web         - not installed          240205           2.1.1        
   duf                - not installed          220809           0.8.1        
   Entware            - not installed          1.03a            1.03a        
   Glances            - not installed          240211           3.4.0.2      
   Headphones         - not installed          240211           0.6.1        
   HideThatBanner     - not installed          240205           240205       
   IncreaseTimeouts   - incompatible QTS version
   inxi               - not installed          240108           3.3.31       
   Kapowarr           - not installed          240211           1.0.0-beta-4 
   LazyLibrarian      - not installed          240211           unknown      
   OLidarr            - incompatible arch   
   OMedusa            - not installed          240211           1.0.19       
   Mylar3             - not installed          240211           0.7.8        
   NZBGet             - not installed          240211           21.1         
   NZBHydra2          - incompatible arch   
   nzbToMedia         - not installed          240205           12.1.12      
   OliveTin           - incompatible arch   
   Par2               - enabled, active        0.8.1.1          0.8.1           /share/MD0_DATA/.qpkg/Par2                   
   Par2turbo          - incompatible arch   
   pyLoad             - not installed          240211           0.5.0        
   OqBittorrent       - not installed          240211           4.5.4        
   QDK                - enabled, active        2.3.13           2.3.13          /share/MD0_DATA/.qpkg/QDK                    
   OReadarr           - incompatible arch   
   RunLast            - not installed          230224           230224       
   SABnzbd            - enabled, inactive      240211           4.2.2           /share/MD0_DATA/.qpkg/SABnzbd                
   sha3sum            - not installed          230312           1.2          
   sherpa             - enabled, active        240212           240212          /share/MD0_DATA/.qpkg/sherpa                 
   OSickGear          - not installed          240211           3.30.9       
   OSonarr            - incompatible arch   
   SortMyQPKGs        - enabled, active        240112           240112          /share/MD0_DATA/.qpkg/SortMyQPKGs            
   OTautulli          - not installed          240211           2.13.4       
   OTransmission      - not installed          240211           4.0.3        
   Unrar              - incompatible arch   
   OWatcher3          - not installed          240211           unknown      
   WebSSH             - not installed          240211           1.6.2        
   OWhisparr          - incompatible arch   

sherpa v240212-stable

done: processing complete.

• These actions were skipped:
      install Entware: no local file found for processing: please report this issue.

• These actions failed:
      download Entware in 1m:03s: 7.
      reactivate ClamAV in 1 second: For more information: /etc/init.d/clamav.sh log
      reactivate SABnzbd in 1 second: For more information: /etc/init.d/sabnzbd.sh log

sherpa v240212-stable

done: processing complete.

• These actions were skipped:
      download Glances: existing file 'Glances_240211.qpkg' checksum correct.
      download Headphones: existing file 'Headphones_240211.qpkg' checksum correct.
      download Kapowarr: existing file 'Kapowarr_240211_x86.qpkg' checksum correct.
      download LazyLibrarian: existing file 'LazyLibrarian_240211_x86.qpkg' checksum correct.
      download OLidarr: NAS arch is incompatible.
      download OMedusa: existing file 'OMedusa_240211.qpkg' checksum correct.
      download Mylar3: existing file 'Mylar3_240211_x86.qpkg' checksum correct.
      download NZBHydra2: NAS arch is incompatible.
      download nzbToMedia: existing file 'nzbToMedia_240205.qpkg' checksum correct.
      download OliveTin: NAS arch is incompatible.
      download pyLoad: existing file 'pyLoad_240211_x86.qpkg' checksum correct.
      download OReadarr: NAS arch is incompatible.
      download SABnzbd: existing file 'SABnzbd_240211_x86.qpkg' checksum correct.
      download OSickGear: existing file 'OSickGear_240211_x86.qpkg' checksum correct.
      download OSonarr: NAS arch is incompatible.
      download OTautulli: existing file 'OTautulli_240211_x86.qpkg' checksum correct.
      download OWatcher3: existing file 'OWatcher3_240211.qpkg' checksum correct.
      download WebSSH: existing file 'WebSSH_240211_x86.qpkg' checksum correct.
      download OWhisparr: NAS arch is incompatible.
      upgrade OLidarr: not installed.
      upgrade OliveTin: not installed.
      upgrade OReadarr: not installed.
      upgrade OSonarr: not installed.
      upgrade OWhisparr: not installed.
      install Entware: no local file found for processing: please report this issue.
      upgrade Glances: not installed.
      upgrade Headphones: not installed.
      upgrade Kapowarr: not installed.
      upgrade LazyLibrarian: not installed.
      upgrade OMedusa: not installed.
      upgrade Mylar3: not installed.
      upgrade NZBHydra2: not installed.
      upgrade nzbToMedia: not installed.
      upgrade pyLoad: not installed.
      upgrade SABnzbd: no new package is available.
      upgrade OSickGear: not installed.
      upgrade OTautulli: not installed.
      upgrade OWatcher3: not installed.
      upgrade WebSSH: not installed.

• These actions failed:
      download Entware in 1m:03s: 7.

[~] #

**Comment by mvught** [comment]
[~] # sherpa install Entware
sherpa v240212-stable

done: processing complete.

• These actions were skipped:
      install Entware: no local file found for processing: please report this issue.

• These actions failed:
      download Entware in 1m:03s: 7.

**Comment by OneCDOnly** [comment]
Hi mate, thanks for reporting this. I'm investigating now...

**Comment by OneCDOnly** [comment]
Works correctly here, so it may be a local problem on your NAS. 

Can you please try running this command? It will attempt to download the Entware QPKG file to your `Public` NAS share:
```
/sbin/curl --verbose --location --output /share/Public/Entware_1.03a_std.qpkg 'http://bin.entware.net/other/Entware_1.03a_std.qpkg'
```
You should see something like this:
```
[~] # /sbin/curl --verbose --location --output /share/Public/Entware_1.03a_std.qpkg 'http://bin.entware.net/other/Entware_1.03a_std.qpkg'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 158.160.45.54:80...
* Connected to bin.entware.net (158.160.45.54) port 80 (#0)
> GET /other/Entware_1.03a_std.qpkg HTTP/1.1
> Host: bin.entware.net
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: nginx/1.22.1
< Date: Sat, 17 Feb 2024 21:08:05 GMT
< Content-Type: application/octet-stream
< Content-Length: 58240
< Last-Modified: Mon, 27 Jun 2022 16:43:29 GMT
< Connection: keep-alive
< ETag: "62b9de31-e380"
< Accept-Ranges: bytes
< 
{ [1144 bytes data]
100 58240  100 58240    0     0  46444      0  0:00:01  0:00:01 --:--:-- 46480
* Connection #0 to host bin.entware.net left intact
```

**Comment by mvught** [comment]
</share/Public/Entware_1.03a_std.qpkg 'http://bin.entware.net/other/Entware_1.03a_std.qpkg'                                              
*   Trying 158.160.45.54...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:02 --:--:--     0* connect to 158.160.45.54 port 80 failed: Connection timed out
* Failed to connect to bin.entware.net port 80: Connection timed out
* Closing connection 0
curl: (7) Failed to connect to bin.entware.net port 80: Connection timed out
[~] #     


ok bizar so its not working..

**Comment by mvught** [comment]
also if I disable my ad-blocker same result here

**Comment by mvught** [comment]
ok if I connect to my hotspot I can download Entware_1.03a_std.qpkg but if I than installed it manually its hanging on 45% is there any output or install log?

**Comment by OneCDOnly** [comment]
Are you in a part of the world that may be blocking access to Russian websites?

**Comment by mvught** [comment]
> Are you in a part of the world that may be blocking access to Russian websites?

Bingo ;) Damm didn't  know that man....

**Comment by mvught** [comment]
done: processing complete.

• These actions completed OK:
      install 96 auxiliary IPK modules in 2m:15s.
      install auxiliary PyPI modules in 25 seconds.
      reactivate ClamAV in 1 second.
      reactivate SABnzbd in 2m:36s.

sherpa v240212-stable

done: processing complete.

**Comment by OneCDOnly** [comment]
Oh nice (so, I've just deleted the reply I was about to send), how did you get it running again?
