### ISSUE TITLE
SABNzbd doesn't work

### ISSUE THREAD

**Issue by jbelvoncik** [OneCDOnly/sherpa#285]
46  source: sabnzbd.sh, action: stop, datetime: Mon Feb 26 13:04:50 CET 2024 
    247 package: 240225, service: 240225, library: 240219
    248 daemon: inactive
    249  source: sabnzbd.sh, action: stop, datetime: Mon Feb 26 13:04:50 CET 2024, result: ok, elapsed time: 109ms 
    250 •
    251  source: sabnzbd.sh, action: start, datetime: Mon Feb 26 13:04:51 CET 2024 
    252 package: 240225, service: 240225, library: 240219
    253 daemon: inactive
    254 auto-update: true
    255 file '/opt/bin/git': exists
    256 update 'SABnzbd' from remote repository: OK
    257 active git branch: 'master'
    258 exclude problem PyPI modules from 'requirements.txt': OK
    259 install PyPI modules from 'requirements.txt': OK
    260 file '/share/CACHEDEV1_DATA/.qpkg/SABnzbd/venv/bin/python3': exists
    261 load ports from configuration file: OK
    262 start daemon: failed
    263 dbug: (LL) adding external log to main log ...
    264 dbug: (LL) ----------------------------------------------------------------------------------------------------
    265 dbug: (LL) = log file: '/var/log/DisplayRunAndLog_8AVUtD'
    266 dbug: (LL) command: '/share/CACHEDEV1_DATA/.qpkg/SABnzbd/venv/bin/python3 /share/CACHEDEV1_DATA/.qpkg/SABnzbd/repo-cache/S    266 ABnzbd.py --daemon --browser 0 --config-file /share/CACHEDEV1_DATA/.qpkg/SABnzbd/config/config.ini --pidfile /var/run/SABn    266 zbd.pid'
    267 dbug: (LL) ! result_code: [1]
    268 dbug: (LL) ••••••••••••••••••••••••••••••••••• stdout & stderr begins below •••••••••••••••••••••••••••••••••••
    269 dbug: (LL) Not all required Python modules are available, please check requirements.txt
    270 dbug: (LL) Missing module: sabctools.sabctools
    271 dbug: (LL) You can read more at: https://sabnzbd.org/wiki/installation/install-off-modules
    272 dbug: (LL) If you still experience problems, remove all .pyc files in this folder and subfolders
    273 dbug: (LL) ••••••••••••••••••••••••••••••••••• stdout & stderr is complete ••••••••••••••••••••••••••••••••••••
    274 dbug: (LL) ----------------------------------------------------------------------------------------------------
    275  source: sabnzbd.sh, action: start, datetime: Mon Feb 26 13:05:10 CET 2024, result: failed, elapsed time: 0h:00m:19s

**Comment by OneCDOnly** [comment]
Hi mate, thanks for reporting this. There was a recent Entware package update that changes how some Python modules can be accessed. 

Can you please run a `clean` on your SABnzbd installation?
```
/etc/init.d/sabnzbd.sh clean
```
... then `start` it:
```
/etc/init.d/sabnzbd.sh start
```

**Comment by jbelvoncik** [comment]
Hi, thank you for your  effort, but
:-( No, 

[~] # /etc/init.d/sabnzbd.sh start
 source: sabnzbd.sh, action: start, datetime: Mon Feb 26 16:41:22 CET 2024 
package: 240225, service: 240225, library: 240219
daemon: inactive
auto-update: true
file '/opt/bin/git': exists
clone 'SABnzbd' from remote repository: OK
active git branch: 'master'
create new virtual Python environment: failed
unable to install addons: 'virtual environment does not exist'
 source: sabnzbd.sh, action: start, datetime: Mon Feb 26 16:41:26 CET 2024, result: failed, elapsed time: 4,602ms

**Comment by OneCDOnly** [comment]
~~OK, Let's try reinstalling your Entware:~~
```
sherpa reinstall ew
```

**Comment by OneCDOnly** [comment]
**Update:** it looks like a `check` is all that's needed to fix this. If you've not yet performed the `reinstall ew` above, please try the `check` first: 
```
sherpa check
```

**Comment by jbelvoncik** [comment]
👍👍👍🙏💪
Thank you all works after EW reinsttall

**Comment by OneCDOnly** [comment]
Good work. :)

If you have any further issues with SABnzbd, please reopen this issue.

**Comment by tranb3r** [comment]
@OneCDOnly 
I'm facing the same error.
I've tried `sherpa check` and `sherpa reinstall ew`.
But SABNzbd still fails to start: `Missing module: sabctools.sabctools`

**Comment by tranb3r** [comment]
I was having the same issue.
I tried `sherpa check` and `sherpa reinstall ew`, but SABNzbd was still failing to start.
Then I tried `/etc/init.d/sabnzbd.sh clean` followed by `/etc/init.d/sabnzbd.sh start`, and it seems to have installed all the requirements, and now it works.
Thanks!
