### ISSUE TITLE
SABnzbd and Mylar3 stopped working

### ISSUE THREAD

**Issue by OneCDOnly** [OneCDOnly/sherpa#287]
### Discussed in https://github.com/OneCDOnly/sherpa/discussions/286

<div type='discussions-op-text'>

<sup>Originally posted by **dltyih** February 28, 2024</sup>
Can anyone help? SABnzbd and Mylar3 suddenly stopped working and remains "inactive" despite being enabled. Tried starting / activating, reinstalling, and uninstall and then install. Sherpa says For more information: /etc/init.d/sabnzbd.sh log. I followed the path and sabnzbd.sh does not appear to be a log? Many thanks</div>

**Comment by OneCDOnly** [comment]
Hi mate, I'll do some testing here and see if Mylar is still working since the recent Entware package upgrade. I'll post back shortly.

**Comment by OneCDOnly** [comment]
Works fine here, so it seems to be a local problem on your NAS. 

@dltyih, can you please run the following commands? 

First, let's activate the Python virtualenv for Mylar:
```
. /share/CACHEDEV1_DATA/.qpkg/Mylar3/venv/bin/activate
```
... Then, check which Mako module your Python virtualenv can see:
```
pip list -v | grep -i mako
```
... and lastly, try importing `mako` as a Python module:
```
python -c "import mako; print("mako.__version__")"
```
Please post back what you see.

**Comment by dltyih** [comment]
Looks like no mako file? I was in Terminal, checked Sherpa Status and confirmed that Mylar3 is still inactive.

I'll attach a screen shot:

![IMG_0454](https://github.com/OneCDOnly/sherpa/assets/16227865/f777ebee-1c01-4ab4-b2b0-6e7bc64da237)

**Comment by OneCDOnly** [comment]
Let's try installing it manually and see if it throws an error. 

Please start by activating the virtual environment again:
```
. /share/CACHEDEV1_DATA/.qpkg/Mylar3/venv/bin/activate
```
... then install the `mako` module:
```
pip install mako
```
... then test import it again:
```
python -c "import mako; print("mako.__version__")"
```
If the import works, we should see this:
```
(venv) [~] # python -c "import mako; print("mako.__version__")"
1.3.0
```

**Comment by dltyih** [comment]
This worked well - thank you so much! Version that got imported was 1.3.2. 

I rebooted the NAS and the two apps are still active. Thank you - really appreciated your help.

**Comment by OneCDOnly** [comment]
Good work. 🤓 

If the problem re-occurs, please reopen this issue, and I'll take another look at it. 

Thanks for reporting this.
