### ISSUE TITLE
QPKG service function library not found

### ISSUE THREAD

**Issue by d9001089** [OneCDOnly/sherpa#288]
Hello, in the last few days I have been getting  "QPKG service function library not found, can't start" on SABnzbd, OWatcher3 & OSickGear. Any ideas what may be causing this?

My config:
Sherpa: 240305, 240305
OSickGear: 240211, 3.30.10
SABnzbd: 240226, 4.2.2
OWatcher3: 240211, unknown
Qnap NAS info:
![image](https://github.com/OneCDOnly/sherpa/assets/17131678/69cb7279-d6a8-4233-b27b-2f5ec8058ed0)

Thanks

**Comment by d9001089** [comment]
Hello, I was able to get everything up and running after reviewing issues #285.  On another note after doing my upgrades yesterday I was no longer able to access my NAS on any of the 4 nic cards. When I tried to ping any of the cards I got either "Destination host unreachable" or "Request timed out". To resolve the issues I had to do a hardware reset using the small button in the back of my NAS.  I'm not saying the upgrades caused the issues but it is a coincidence that you may be interested in.  

Finally, Thank you.... I have been using your products for years and I am extremely satisfied with your work and all the effort you put into OneCDOnly :-)

**Comment by OneCDOnly** [comment]
Good work mate. 🤓 

With regard to the "unreachable" error, I suspect your NAS was too-busy to respond. Which sherpa QPKGs are installed please? 

I'll reopen this issue for now.

**Comment by d9001089** [comment]
Hello I have SABnzbd, Owatcher & Sickgear running on my set however at the
time I encountered the issue I was just upgrading Sherpa and SAB. As far as
the unreachable error issue persisted for at least 24hrs until I was able
to do a hardware nas reset

**Comment by OneCDOnly** [comment]
Okidoke, thank you. I've not encountered that myself so I'll keep an eye-out for it. 

Cheers! 🤓
