### ISSUE TITLE
Issue updating

### ISSUE THREAD

**Issue by DynaMight1124** [OneCDOnly/sherpa#297]
Hi

Every few weeks or so I usually do a 'sherpa upgrade all' last time was 15/09 so ran one today.

When I originally ran upgrade all, I got this:
sherpa v240930-stable
warn: the 'Qboost' QPKG is enabled. This may cause problems with sherpa applications. Please consider stopping this QPKG in your App Center.
proc: assign QPKGs by state ... mknod: `/var/run/sherpa/packages/states/action.messages.pipe': No such file or directory
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa-manager.sh: line 1233: /var/run/sherpa/packages/states/action.messages.pipe: No such file or directory
proc: upgrade independent QPKGs ... 100% (19/19), 19 skippedstatus|ex|package|OWhisparr

Had to CTRL+C to end. So I upgraded sherpa only and it did successfully upgrade so then did another upgrade all, it seemingly ran successfully however didnt upgrade any packages.

Output was:
sudo sherpa upgrade all
sherpa v240930-stable
warn: the 'Qboost' QPKG is enabled. This may cause problems with sherpa applications. Please consider stopping this QPKG in your App Center.
done: actions complete.
      upgrade TorrServer QPKG (incompatible author)
      upgrade Unrar QPKG (no new QPKG is available)
      upgrade OWhisparr QPKG (incompatible author)
      upgrade Bazarr QPKG (incompatible author)
      upgrade ClamAV QPKG (incompatible author)
      upgrade Glances QPKG (incompatible author)
      upgrade Headphones QPKG (incompatible author)
      upgrade inxi QPKG (incompatible author)
      upgrade Kapowarr QPKG (incompatible author)
      upgrade LazyLibrarian QPKG (incompatible author)
      upgrade OMedusa QPKG (incompatible author)
      upgrade Mylar3 QPKG (incompatible author)
      upgrade NZBHydra2 QPKG (incompatible author)
      upgrade nzbToMedia QPKG (incompatible author)
      upgrade pyLoad QPKG (incompatible author)
      upgrade OqBittorrent QPKG (incompatible author)
      upgrade SABnzbd QPKG (no new QPKG is available)
      upgrade OSickGear QPKG (incompatible author)
      upgrade OTautulli QPKG (incompatible author)
      upgrade OTransmission QPKG (no new QPKG is available)
      upgrade Unmanic QPKG (incompatible author)
      upgrade OWatcher3 QPKG (incompatible author)
      upgrade WebSSH QPKG (incompatible author)

Its a TS251B device so should be ok with any newer packages?

Thanks
Gavin

**Comment by OneCDOnly** [comment]
Hey Gavin. 🤓 

The TS-251B should be fine (I run sherpa on a TS-251+ without error). 

I'm investigating that `mknod` error now... I'll post back shortly.

**Comment by OneCDOnly** [comment]
I've made a tweak, but it's only available in the `unstable` branch for-now. 

If you'd like to try it, please run:
```
sherpa follow unstable
sherpa upgrade new
```
If you get the same `mknod` error, please manually stop with CTRL+C again, and let me know. 

To revert back to the `stable` branch (I don't recommend staying on `unstable` as it's ... unstable. 😉  ):
```
sherpa reset
```

**Comment by DynaMight1124** [comment]
Hi, thanks for getting back to me.

That worked perfect.

done: user setting 'Git_Branch = unstable' has been saved.
done: package cache cleared.
done: reports cleared.
done: logs cleared.



sudo sherpa upgrade new
sherpa v241001-unstable
warn: the 'Qboost' QPKG is enabled. This may cause problems with sherpa applications. Please consider stopping this QPKG in your App Center.
note: the sherpa QPKG will be auto-upgraded.
done: actions complete.

• Package actions started @ 10:31:35 PM, ended @ 10:32:58 PM, elapsed = 1m:23s

• These package actions completed OK:
      download SABnzbd QPKG in 1 second
      download sherpa QPKG in 1 second
      download OSonarr QPKG in 1 second
      download OTransmission QPKG in 1 second
      deactivate OTransmission QPKG in 2 seconds
      deactivate OSonarr QPKG in 2 seconds
      upgrade sherpa QPKG in 12 seconds (v240930 -> v241001)
      upgrade OSonarr QPKG in 12 seconds (v240915 -> v240930)
      activate sherpa QPKG in 1 second
      activate Entware QPKG in 1 second
      activate OSonarr QPKG in 14 seconds
      upgrade SABnzbd QPKG in 8 seconds (v240915 -> v240930)
      upgrade OTransmission QPKG in 12 seconds (v240915 -> v240930)
      activate OTransmission QPKG in 3 seconds

I have reverted back to the stable branch. 

Thank you for having a look, sorry for raising the issue, never quite sure if I'm nitpicking or raising something that helps.

Thanks
Gavin

**Comment by OneCDOnly** [comment]
@DynaMight1124 

That's great. Thanks for reporting this and for testing the fix. 👍🏽 

This fix will be available in the next `stable` release (should be less-than 24 hours from-now).

Yes, it's OK to question any-and-all errors you see. Especially ugly shell errors that occur in the midst of a sherpa message. I'm glad you mentioned this, else I wouldn't have known this problem existed. 

Cheers! 🤓
