### ISSUE TITLE
Upgrade All not working?

### ISSUE THREAD

**Issue by DynaMight1124** [OneCDOnly/sherpa#299]
Hi

Sorry me again, I've always used 'upgrade all' when updating my packages and its always worked however the last few times it hasnt worked as usual. I've used 'upgrade new' and its worked.

Am I mis understanding upgrade all? or is there an issue?

Thanks

Heres the Putty log:

sudo sherpa upgrade all

sherpa v241205-stable
warn: the 'Qboost' QPKG is enabled. This may cause problems with sherpa applications. Please consider stopping this QPKG in your App Center.
done: actions complete.

• Package actions started @ 7:20:30 PM, ended @ 7:20:48 PM, elapsed = 18 seconds

• These package actions were skipped (and why):
      upgrade duf QPKG (not installed)
      upgrade Entware QPKG (no new QPKG is available)
      upgrade HideThatBanner QPKG (not installed)
      upgrade IncreaseTimeouts QPKG (not installed)
      upgrade OLidarr QPKG (not installed)
      upgrade nzbget QPKG (no new QPKG is available)
      upgrade OliveTin QPKG (not installed)
      upgrade Par2 QPKG (not installed)
      upgrade Par2turbo QPKG (no new QPKG is available)
      upgrade QDK QPKG (not installed)
      upgrade OReadarr QPKG (not installed)
      upgrade RunLast QPKG (not installed)
      upgrade sha3sum QPKG (not installed)
      upgrade sherpa QPKG (no new QPKG is available)
      upgrade OSonarr QPKG (no new QPKG is available)
      upgrade SortMyQPKGs QPKG (no new QPKG is available)
      upgrade TorrServer QPKG (not installed)
      upgrade TrguiNG QPKG (not installed)
      upgrade Unrar QPKG (no new QPKG is available)

sudo sherpa upgrade new
sherpa v241205-stable
warn: the 'Qboost' QPKG is enabled. This may cause problems with sherpa applications. Please consider stopping this QPKG in your App Center.
done: actions complete.

• Package actions started @ 7:22:05 PM, ended @ 7:23:56 PM, elapsed = 1m:51s

• These package actions completed OK:
      download SABnzbd QPKG in 1 second
      download OSonarr QPKG in 1 second
      download OTransmission QPKG in 1 second
      download nzbget QPKG in 1 second
      deactivate SABnzbd QPKG in 2 seconds
      deactivate OTransmission QPKG in 3 seconds
      deactivate nzbget QPKG in 1 second
      deactivate OSonarr QPKG in 2 seconds
      upgrade nzbget QPKG in 15 seconds (v24.4 -> v24.5)
      upgrade OSonarr QPKG in 13 seconds (v241030 -> v241204)
      activate nzbget QPKG in 1 second
      activate Entware QPKG in 1 second
      activate Par2turbo QPKG in 1 second
      activate Unrar QPKG in 1 second
      activate OSonarr QPKG in 15 seconds
      upgrade SABnzbd QPKG in 13 seconds (v241030 -> v241204)
      upgrade OTransmission QPKG in 13 seconds (v241030 -> v241204)
      activate OTransmission QPKG in 4 seconds
      activate SABnzbd QPKG in 20 seconds

**Comment by OneCDOnly** [comment]
Hi @DynaMight1124 🤓 

Looks OK.

A while back, I fixed an inconsistency when specifying `all` where it was only applied to `installed` QPKGs. It now correctly uses `all` to mean all QPKGs in sherpa. In most cases, this will result in actions being skipped because not every package is installed. Because, if it's not installed, it can't be upgraded. 

Your use of `upgrade new` is exactly right. This only upgrades packages that are already installed and a newer package version has been found. (`new` is essentially a shortcode meaning `installed` and `upgradable`.)

**Comment by DynaMight1124** [comment]
Thats cool, I've always used upgrade all and always read it all 'upgrade all your installed packages' but using upgrade new makes sense. Thanks for coming back to me.
