### ISSUE TITLE
Upgrade Medusa Python version to >= 3.5

### ISSUE THREAD

**Issue by medariox** [OneCDOnly/sherpa#31]
Hello! Medusa dev here ✋ 

We have noticed that your script is a popular way to install Medusa! 🎉 
I'm here to inform you that we are fully Python 3 compatible since a few releases.

As you may already know Python 2.7 has reached its EOL on 01.01.2020. 
For this reason we will end support for any Medusa installs using Python 2.7 in the near future.

We kindly ask you to update the Python version to >= 3.5 (preferably 3.6 or 3.7) as soon as possible. The update won't require any intervention from the end users.

Thank you for your continued support 👏

**Comment by OneCDOnly** [comment]
Thanks for the update Dario, this is now done. :+1:
