### ISSUE TITLE
update fail due to pip3 missing, QTS-4.3.6, sabnzbdplus

### ISSUE THREAD

**Issue by 2bits** [OneCDOnly/sherpa#43]
Using sherpa.sh I've been running sabnzbdplus on QTS 4.3.6.1070 for maybe a year now.  Recently I ran into some par2 failures and decided to see if I could update anything using sherpa.sh.  When I tried to update, I got a Fail message about pip3 not being found.

### Details:
sabnzbd is running and has been working well, except for the occasional par2 failure.

I downloaded the latest sherpa.sh following the directions on p1 of the forum thread.

I ran --update-all, and this is the error I got.

```
[/share/Public] # ./sherpa.sh --update-all
sherpa.sh (200610)

[ done ] Internet is accessible            
[ done ] updated 'Entware' package list            
[ done ] 2 IPKGs (292kB) to be downloaded                              
[ done ] downloaded & installed 2 IPKGs                         
[ done ] downloaded & installed Python 2 modules             
[ fail ] A required NAS system file is missing (/opt/bin/pip3) 
```

I haven't tried to fix it yet.  I would need specific directions I think.
Here's [sherpa.debug.log](https://github.com/OneCDOnly/sherpa/files/4755852/sherpa.debug.log)
 
Thanks for working on this!

**Comment by OneCDOnly** [comment]
Hi and thanks for posting your log. 

OK, the good news is: this problem should no longer occur as of about 2 weeks ago. 

The bad news is: you'll need to reinstall your Entware for the fix to "take-effect". You can do this with:

```
./sherpa.sh ew
```
After this, if you see a pip3 missing error again, please advise. :+1:

**Comment by 2bits** [comment]
That command worked great, thank you.
