### ISSUE TITLE
Entware QPKG install failed - started as update failed.

### ISSUE THREAD

**Issue by OU812-me2** [OneCDOnly/sherpa#62]
Entware QPKG install failed - started as update failed.
Pastebin file here: https://l.termbin.com/492d

[ done ] downloaded QPKG (Entware_1.02std.qpkg)
[ note ] Reinstalling 'Entware' will revert all IPKGs to defaults and only those required to support your sherpa apps will be reinstalled.
[ note ] The currently installed IPKG list will be saved to (/share/Public/Entware.previously.installed.list)
[ warn ] Also, the 'SABnzbdplus' and 'Headphones' packages CANNOT BE REINSTALLED as Python 2.7.16 is no-longer available.
[ quiz ] Press (y) if you agree to remove all current 'Entware' IPKGs and their configs, or any other key to abort: y
[ proc ] uninstalling 'Entware' ...
[ done ] uninstalled 'Entware'
[ fail ] QPKG installation failed (Entware_1.02std.qpkg) [1]
grep: : No such file or directory
sed: : No such file or directory
sed: : No such file or directory
[ fail ] 'Entware' reinstall failed! [23]

**Comment by OneCDOnly** [comment]
Hi, and thanks for posting your log to termbin. :+1: 

It looks like the problem is that your TarMT QPKG is using [/opt] just like Entware. :disappointed: 

Can you please uninstall the TarMT QPKG, reinstall Entware again (via sherpa), then reinstall TarMT? I think that should fix things.

**Comment by OU812-me2** [comment]
Thanks! I removed TarMT as suggested but no joy.... New termbin file: https://l.termbin.com/boyr

[/share/Public] # ./sherpa.sh Entware
sherpa.sh (200809e)

[ fail ] QPKG installation failed (Entware_1.02std.qpkg) [1]
grep: : No such file or directory
sed: : No such file or directory
sed: : No such file or directory
[ fail ] 'Entware' install failed! [23]

**Comment by OneCDOnly** [comment]
Can you please logout that SSH session, then back-in again? Then check your $PATH:
```
echo $PATH
```

**Comment by OU812-me2** [comment]
Yes, thanks again!

[~] # echo $PATH
/share/CACHEDEV1_DATA/.qpkg/container-station/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/bin/X11:/usr/local/sbin:/usr/local/bin:/usr/local/jre/bin

**Comment by OneCDOnly** [comment]
Look good. :+1: 

Is your /opt directory still there?
```
ll /opt
```
If so, what's in it? 
```
ll /opt/
```

**Comment by OU812-me2** [comment]
It's gone. Whoa!

[~] # ll /opt/
/bin/ls: cannot access /opt/: No such file or directory
[~] # cd /opt
-sh: cd: /opt: No such file or directory

**Comment by OneCDOnly** [comment]
That's good news. :+1: 

OK, now try installing something via sherpa.

**Comment by OU812-me2** [comment]
Thanks! Should I try something other than EW? https://l.termbin.com/f84v

[/share/Public] # ./sherpa.sh Entware
sherpa.sh (200809e)

[ fail ] QPKG installation failed (Entware_1.02std.qpkg) [1]
grep: : No such file or directory
sed: : No such file or directory
sed: : No such file or directory
[ fail ] 'Entware' install failed! [23]

**Comment by OneCDOnly** [comment]
Hmm, I'm wondering if that TarMT QPKG has temporarily discarded the QTS `tar` binary. 

I hope not as it's needed to install other QPKGs. 

Is there any tar available? 
```
type -a tar
```

**Comment by OU812-me2** [comment]
I think you're onto something. 

`[/share/Public] # type -a tar
-sh: type: tar: not found`

[/share/Public] # ll /bin/tar
/bin/ls: cannot access /bin/tar: No such file or directory

**Comment by OneCDOnly** [comment]
OK, I guess the TarMT QPKG doesn't restore access to the original tar binary when it uninstalls. Something you might want to report to QNAP_Stephane when you get time. :wink: 

The simple fix is to reboot your NAS. :nerd_face:

**Comment by OU812-me2** [comment]
LOL I should have tried that to begin with. Trying that now. Mine takes about 15-20 minutes to reboot. I'll ping back after I've rebooted and tried to reinstall EW

**Comment by OneCDOnly** [comment]
Okiedoke, good luck! :wink:

**Comment by OneCDOnly** [comment]
Also, if you have Entware installed, you don't need the TarMT QPKG. You can install a later version of tar via `opkg` with:
```
opkg install tar
```

**Comment by OU812-me2** [comment]
That is a great idea! Thank you!

**Comment by OU812-me2** [comment]
Thank you!! You're the best! its not done yet but already in a good spot.
[~] # cd /share/Public
[/share/Public] # curl -skLO https://git.io/sherpa.sh && chmod +x sherpa.sh
[/share/Public] # ./sherpa.sh Entware
sherpa.sh (200809f)

[ done ] installed QPKG (Entware_1.02std.qpkg)
[ done ] 'Entware' package list is up-to-date
[ done ] 65 IPKGs (28MB) to be downloaded
[ proc ] downloading & installing 65 IPKGs ... 89% (25MB/28MB)

**Comment by OneCDOnly** [comment]
Cheers mate, good work! :champagne:

**Comment by OneCDOnly** [comment]
I think this is OK now. If not, please reopen! :+1:
