### ISSUE TITLE
error installing SABnzbd - fails on  Download & install 'Python 3'

### ISSUE THREAD

**Issue by entrican** [OneCDOnly/sherpa#86]
About 5 days ago I noticed SABnzbd was no longer working on my QNAP.  It would not start and the log indicated it was because it could not locate Python 3.5 - which is installed, the startup script for SABnzbd has a reference to 2.7 in it.  Anyhow, I thought it would be cleanest to simply re-run the sherpa.sh SABnzbd install to get the latest SABnzbd codebase instead of hacking up my local install only to break later when something I've edited gets overwritten.

The sherpa.sh fails trying to get Python 3 with an error that suggests it cannot negotiate an SSL session because of a missing library.  Here are all the pertinent details.  I'm hoping you've already heard of this and have a potential solution.

QNAP TS-453A
FW Version: 4.3.4.0695

[/share/Public] # ./sherpa.sh SABnzbd
sherpa.sh (200819d)

[ done ] downloaded QPKG (SABnzbd_200819b.qpkg)
[ done ] 'Entware' package list is up-to-date
[ done ] no IPKGs are required
[ fail ] Download & install 'Python 3' modules failed ! result: [1]
[ fail ] 'SABnzbd' install failed! [0]

* Please consider creating a new issue for this on GitHub:
        https://github.com/OneCDOnly/sherpa/issues

* Alternatively, post on the QNAP NAS Community Forum:
        https://forum.qnap.com/viewtopic.php?f=320&t=132373

* Remember to include a copy of your sherpa log for analysis.

- View the sherpa log:
        ./sherpa.sh --log

- Upload the sherpa log to a public pastebin (https://termbin.com):
        ./sherpa.sh --paste

[/share/Public] #

--------------------------------------------------------------------------------------------------------
START OF sherpa.debug.log
--------------------------------------------------------------------------------------------------------

[ dbug ] (II) ========================================================================
[ dbug ] (**) SCRIPT:             started: Wed Aug 19 14:15:01 PDT 2020
[ dbug ] (**) SCRIPT:             version: 200819d
[ dbug ] (**) SCRIPT:                 PID: 25945
[ dbug ] (II) ------------------------------------------------------------------------
[ dbug ] (II) Markers: (**) detected, (II) information, (WW) warning, (LL) log file,
[ dbug ] (II)  (EE) error, (==) processing, (--) done, (>>) f entry, (<<) f exit,
[ dbug ] (II)  (vv) variable name & value, ($1) positional argument value.
[ dbug ] (II) ------------------------------------------------------------------------
[ dbug ] (**) NAS   :               model: TS-453A
[ dbug ] (**) NAS   :                 RAM: 3947492 kB
[ dbug ] (**) NAS   :    firmware version: 4.3.4
[ dbug ] (**) NAS   :      firmware build: 20180830
[ dbug ] (**) NAS   :              kernel: 4.2.8 x86_64
[ dbug ] (**) NAS   :           OS uptime: 4 days
[ dbug ] (**) NAS   :         system load: 1 min=2.03, 5 min=2.08, 15 min=1.93
[ dbug ] (**) NAS   :                USER: admin
[ dbug ] (**) NAS   :                EUID: 0
[ dbug ] (**) NAS   :      default volume: /share/CACHEDEV1_DATA
[ dbug ] (**) NAS   :               $PATH: /share/CACHEDEV1_DATA/.qpkg/Python3/python3
[ dbug ] (**) NAS   :                /opt: /share/CACHEDEV1_DATA/.qpkg/Entware
[ dbug ] (**) NAS   :     /share/Download: CACHEDEV1_DATA/Download
[ dbug ] (**) SCRIPT:  unparsed arguments: SABnzbd
[ dbug ] (**) SCRIPT:   app(s) to install: SABnzbd
[ dbug ] (**) SCRIPT: app(s) to uninstall:
[ dbug ] (**) SCRIPT: app(s) to reinstall:
[ dbug ] (**) SCRIPT:    app(s) to update:
[ dbug ] (**) SCRIPT:    app(s) to backup:
[ dbug ] (**) SCRIPT:   app(s) to restore:
[ dbug ] (**) SCRIPT:           work path: /share/Public/sherpa.tmp
[ dbug ] (**) QPKG  :       download path: /share/Public/sherpa.tmp/qpkg.downloads
[ dbug ] (**) IPKG  :       download path: /share/Public/sherpa.tmp/ipkg.downloads
[ dbug ] (**) QPKG  :                arch: x64
[ dbug ] (II) ------------------------------------------------------------------------
[ dbug ] (**) QPKG  :   Entware installer: std
[ dbug ] (II) ------------------------------------------------------------------------
[ dbug ] (>>) DownloadQPKGs()
[ dbug ] (>>) DownloadQPKG()
[ proc ] downloading QPKG (SABnzbd_200819b.qpkg) ...
[ done ] downloaded QPKG (SABnzbd_200819b.qpkg)
[ dbug ] (<<) DownloadQPKG() [0]
[ dbug ] (<<) DownloadQPKGs() [0]
[ dbug ] (**) QPKG  :           'Optware': not installed [250]
[ dbug ] (**) QPKG  :        'Entware-3x': not installed [250]
[ dbug ] (**) QPKG  :        'Entware-ng': not installed [250]
[ dbug ] (>>) InstallQPKGIndeps()
[ dbug ] (II) patch: do the "opt shuffle" - already done
[ dbug ] (<<) InstallQPKGIndeps() [0]
[ dbug ] (>>) InstallQPKGIndepsAddons()
[ dbug ] (>>) InstallIPKGs()
[ dbug ] (II) 'Entware' package list was updated less than 60 minutes ago
[ done ] 'Entware' package list is up-to-date
[ dbug ] (>>) InstallIPKGBatch()
[ dbug ] (II) ------------------------------------------------------------------------
[ dbug ] (**) STAGE :   start stage timer
[ proc ] determining IPKGs required ...
[ dbug ] (II) IPKGs requested: ca-certificates coreutils-nice ffprobe gcc git git-http ionice less nano p7zip python3 python3-cryptography python3-dev python3-pip python3-pyopenssl unrar
[ dbug ] (==) finding IPKG dependencies ...
[ dbug ] (--) complete
[ dbug ] (II) found all IPKG dependencies in 13 iterations
[ dbug ] (II) IPKGs requested + dependencies: alsa-lib ar binutils ca-bundle ca-certificates ca-certs coreutils coreutils-nice ffprobe file gcc git git-http ionice lame-lib less libatomic libbfd libbz2 libc libcurl libdb47 libexpat libffi libffmpeg-full libgcc libgdbm libgmp libgnutls libiconv-full libintl-full liblzma libmagic libncurses libncursesw libnettle libopcodes libopenssl libopus libpthread librt libsqlite3 libssp libstdcpp libtirpc libuuid libx264 libxml2 nano objdump p7zip python-pip-conf python3 python3-asyncio python3-base python3-cffi python3-cgi python3-cgitb python3-codecs python3-cryptography python3-ctypes python3-dbm python3-decimal python3-dev python3-distutils python3-email python3-gdbm python3-lib2to3 python3-light python3-logging python3-lzma python3-multiprocessing python3-ncurses python3-openssl python3-pip python3-pkg-resources python3-ply python3-pycparser python3-pydoc python3-pyopenssl python3-setuptools python3-six python3-sqlite3 python3-unittest python3-urllib python3-xml terminfo unrar zlib
[ dbug ] (**) STAGE :        elapsed time: 00h:00m:02s
[ dbug ] (II) ------------------------------------------------------------------------
[ dbug ] (==) excluding IPKGs already installed ...
[ dbug ] (--) complete
[ dbug ] (II) IPKGs to download:
[ done ] no IPKGs are required
[ dbug ] (<<) InstallIPKGBatch() [0]
[ dbug ] (<<) InstallIPKGs() [0]
[ dbug ] (>>) InstallPy3Modules()
[ proc ] downloading & installing 'Python 3' modules ...
[ dbug ] (vv) $abort [true]
[ dbug ] (vv) $error [true]
[ fail ] Download & install 'Python 3' modules failed ! result: [1]
[ dbug ] (LL) ------------------------------------------------------------------------
[ dbug ] (LL) /share/Public/sherpa.tmp/py3-modules.install.log
[ dbug ] (LL) ------------------------------------------------------------------------
[ dbug ] (LL) = command: '/opt/bin/pip3 install setuptools --disable-pip-version-check --cache-dir /share/Public/sherpa.tmp/pip.cache && /opt/bin/pip3 install   sabyenc3 cheetah3 feedparser configobj cherrypy chardet "cheroot!=8.4.4" asn1crypto random_user_agent pygithub      --disable-pip-version-check --cache-dir /share/Public/sherpa.tmp/pip.cache && /opt/bin/pip3 install --force-reinstall --ignore-installed --no-binary :all: sabyenc3 --disable-pip-version-check --cache-dir /share/Public/sherpa.tmp/pip.cache'
[ dbug ] (LL) ! result: [1] â~V¼ â~V¼ â~V¼ stdout begins below â~V¼ â~V¼ â~V¼
[ dbug ] (LL) WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
[ dbug ] (LL) Requirement already satisfied: setuptools in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.8/site-packages (41.2.0)
[ dbug ] (LL) WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
[ dbug ] (LL) Collecting sabyenc3
[ dbug ] (LL) WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/sabyenc3/
[ dbug ] (LL) WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/sabyenc3/
[ dbug ] (LL) WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/sabyenc3/
[ dbug ] (LL) WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/sabyenc3/
[ dbug ] (LL) WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/sabyenc3/
[ dbug ] (LL) Could not fetch URL https://pypi.org/simple/sabyenc3/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/sabyenc3/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
[ dbug ] (LL) ERROR: Could not find a version that satisfies the requirement sabyenc3 (from versions: none)
[ dbug ] (LL) ERROR: No matching distribution found for sabyenc3
[ dbug ] (LL) = â~V² â~V² â~V² stdout is complete â~V² â~V² â~V²
[ dbug ] (LL) ------------------------------------------------------------------------
[ dbug ] (<<) InstallPy3Modules() [0]
[ dbug ] (<<) InstallQPKGIndepsAddons() [0]
[ fail ] 'SABnzbd' install failed! [0]
[ dbug ] (vv) $suggest_issue [true]
[ dbug ] (II) ------------------------------------------------------------------------
[ dbug ] (**) SCRIPT:            finished: Wed Aug 19 14:15:15 PDT 2020
[ dbug ] (**) SCRIPT:        elapsed time: 00h:00m:14s
[ dbug ] (II) ========================================================================
[ dbug ] (II) ========================================================================
[ dbug ] (**) SCRIPT:             started: Wed Aug 19 14:17:32 PDT 2020
[ dbug ] (**) SCRIPT:             version: 200819d
[ dbug ] (**) SCRIPT:                 PID: 29148
[ dbug ] (II) ------------------------------------------------------------------------
[ dbug ] (II) Markers: (**) detected, (II) information, (WW) warning, (LL) log file,
[ dbug ] (II)  (EE) error, (==) processing, (--) done, (>>) f entry, (<<) f exit,
[ dbug ] (II)  (vv) variable name & value, ($1) positional argument value.
[ dbug ] (II) ------------------------------------------------------------------------
[ dbug ] (vv) $abort [true]
[ dbug ] (vv) $logpaste_only [true]
[ quiz ] Press 'Y' to post your sherpa log in a public pastebin, or any other key to abort
[ dbug ] (vv) $response []
[ dbug ] (vv) $show_installer_outcome [false]
[ dbug ] (II) ------------------------------------------------------------------------
[ dbug ] (**) SCRIPT:          user abort
[ dbug ] (II) ========================================================================
[ dbug ] (II) ------------------------------------------------------------------------
[ dbug ] (**) SCRIPT:            finished: Wed Aug 19 14:17:40 PDT 2020
[ dbug ] (**) SCRIPT:        elapsed time: 00h:00m:08s
[ dbug ] (II) ========================================================================

**Comment by OneCDOnly** [comment]
Hi and thanks for posting your log. 👍🏽 

It looks like Entware will need to be reinstalled. 

Please download the latest **sherpa.sh** script:
```
cd /share/Public && curl -skLO https://git.io/sherpa.sh && chmod +x sherpa.sh
```
... and reinstall Entware:
```
./sherpa.sh ew
```

BTW: some good news. After downloading this sherpa.sh, you'll no longer need to download it to ensure you have the latest version. It will now grab the latesting installation information from this repo. 😄

**Comment by entrican** [comment]
Thank you for the quick reply!  I had fetched the latest sherpa, but did it again to be safe and re-installed "ew".  I noticed during the install it complained about not being able to launch SickChill but I decided to look at that after the fact.  After it completed the install of Entware, I reinstalled "SABnzbd" and it did in fact finish, but when I tried to restart SABnzbd, it failed with the following error.

[/share/Public] # /etc/init.d/sabnzbd.sh start
= (SABnzbdplus) is not active
* updating (SABnzbdplus): OK
* updating language support (SABnzbdplus): OK
* updating (nzbToMedia): OK
* starting (SABnzbdplus): failed!
result=[127]
/etc/init.d/sabnzbd.sh: line 156: /opt/bin/python2.7: No such file or directory

Appears even after re-installing with sherpa, SABnzbd is still looking for 2.7 in it's init script.

If this is outside of sherpa, please let me know and I'll keep digging, but I thouht when I did the install, it would pull down the latest and re-install SABnzbd for me.

----------------------------------------------------------------------
sherpa.debug.log
----------------------------------------------------------------------

[ dbug ] (II) ========================================================================
[ dbug ] (**) SCRIPT:             started: Wed Aug 19 14:50:26 PDT 2020
[ dbug ] (**) SCRIPT:             version: 200820c
[ dbug ] (**) SCRIPT:                 PID: 29881
[ dbug ] (II) ------------------------------------------------------------------------
[ dbug ] (II) Markers: (**) detected, (II) information, (WW) warning, (LL) log file,
[ dbug ] (II)  (EE) error, (==) processing, (--) done, (>>) f entry, (<<) f exit,
[ dbug ] (II)  (vv) variable name & value, ($1) positional argument value.
[ dbug ] (II) ------------------------------------------------------------------------
[ dbug ] (**) NAS   :               model: TS-453A
[ dbug ] (**) NAS   :                 RAM: 3947492 kB
[ dbug ] (**) NAS   :    firmware version: 4.3.4
[ dbug ] (**) NAS   :      firmware build: 20180830
[ dbug ] (**) NAS   :              kernel: 4.2.8 x86_64
[ dbug ] (**) NAS   :           OS uptime: 4 days
[ dbug ] (**) NAS   :         system load: 1 min=1.38, 5 min=1.93, 15 min=1.91
[ dbug ] (**) NAS   :                USER: admin
[ dbug ] (**) NAS   :                EUID: 0
[ dbug ] (**) NAS   :      default volume: /share/CACHEDEV1_DATA
[ dbug ] (**) NAS   :               $PATH: /share/CACHEDEV1_DATA/.qpkg/Python3/python3
[ dbug ] (**) NAS   :                /opt: /share/CACHEDEV1_DATA/.qpkg/Entware
[ dbug ] (**) NAS   :     /share/Download: CACHEDEV1_DATA/Download
[ dbug ] (**) SCRIPT:  unparsed arguments: SABnzbd
[ dbug ] (**) SCRIPT:   app(s) to install: SABnzbd
[ dbug ] (**) SCRIPT: app(s) to uninstall:
[ dbug ] (**) SCRIPT: app(s) to reinstall:
[ dbug ] (**) SCRIPT:    app(s) to update:
[ dbug ] (**) SCRIPT:    app(s) to backup:
[ dbug ] (**) SCRIPT:   app(s) to restore:
[ dbug ] (**) SCRIPT:           work path: /share/Public/sherpa.tmp
[ dbug ] (**) QPKG  :       download path: /share/Public/sherpa.tmp/qpkg.downloads
[ dbug ] (**) IPKG  :       download path: /share/Public/sherpa.tmp/ipkg.downloads
[ dbug ] (**) QPKG  :                arch: x64
[ dbug ] (II) ------------------------------------------------------------------------
[ dbug ] (**) QPKG  :   Entware installer: std
[ dbug ] (II) ------------------------------------------------------------------------
[ dbug ] (>>) DownloadQPKGs()
[ dbug ] (>>) DownloadQPKG()
[ proc ] downloading QPKG (SABnzbd_200820.qpkg) ...
[ done ] downloaded QPKG (SABnzbd_200820.qpkg)
[ dbug ] (<<) DownloadQPKG() [0]
[ dbug ] (<<) DownloadQPKGs() [0]
[ dbug ] (**) QPKG  :           'Optware': not installed [250]
[ dbug ] (**) QPKG  :        'Entware-3x': not installed [250]
[ dbug ] (**) QPKG  :        'Entware-ng': not installed [250]
[ dbug ] (>>) InstallQPKGIndeps()
[ dbug ] (II) patch: do the "opt shuffle" - already done
[ dbug ] (<<) InstallQPKGIndeps() [0]
[ dbug ] (>>) InstallQPKGIndepsAddons()
[ dbug ] (>>) InstallIPKGs()
[ dbug ] (II) 'Entware' package list was updated less than 60 minutes ago
[ done ] 'Entware' package list is up-to-date
[ dbug ] (>>) InstallIPKGBatch()
[ dbug ] (II) ------------------------------------------------------------------------
[ dbug ] (**) STAGE :   start stage timer
[ proc ] determining IPKGs required ...
[ dbug ] (II) IPKGs requested: ca-certificates coreutils-nice ffprobe gcc git git-http ionice less nano p7zip python3 python3-cryptography python3-dev python3-pip python3-pyopenssl unrar
[ dbug ] (==) finding IPKG dependencies ...
[ dbug ] (--) complete
[ dbug ] (II) found all IPKG dependencies in 13 iterations
[ dbug ] (II) IPKGs requested + dependencies: alsa-lib ar binutils ca-bundle ca-certificates ca-certs coreutils coreutils-nice ffprobe file gcc git git-http ionice lame-lib less libatomic libbfd libbz2 libc libcurl libdb47 libexpat libffi libffmpeg-full libgcc libgdbm libgmp libgnutls libiconv-full libintl-full liblzma libmagic libncurses libncursesw libnettle libopcodes libopenssl libopus libpthread librt libsqlite3 libssp libstdcpp libtirpc libuuid libx264 libxml2 nano objdump p7zip python-pip-conf python3 python3-asyncio python3-base python3-cffi python3-cgi python3-cgitb python3-codecs python3-cryptography python3-ctypes python3-dbm python3-decimal python3-dev python3-distutils python3-email python3-gdbm python3-lib2to3 python3-light python3-logging python3-lzma python3-multiprocessing python3-ncurses python3-openssl python3-pip python3-pkg-resources python3-ply python3-pycparser python3-pydoc python3-pyopenssl python3-setuptools python3-six python3-sqlite3 python3-unittest python3-urllib python3-xml terminfo unrar zlib
[ dbug ] (**) STAGE :        elapsed time: 00h:00m:02s
[ dbug ] (II) ------------------------------------------------------------------------
[ dbug ] (==) excluding IPKGs already installed ...
[ dbug ] (--) complete
[ dbug ] (II) IPKGs to download: alsa-lib ar binutils coreutils coreutils-nice ffprobe gcc ionice lame-lib libatomic libbfd libffmpeg-full libgmp libgnutls libiconv-full libintl-full libnettle libopcodes libopus libx264 objdump p7zip python3-cffi python3-cryptography python3-dev python3-lib2to3 python3-ply python3-pycparser python3-pyopenssl python3-six unrar
[ dbug ] (==) determining size of IPKGs to download ...
[ dbug ] (--) complete
[ dbug ] (vv) $IPKG_download_size [85897779]
[ done ] 31 IPKGs (86MB) to be downloaded
[ dbug ] (II) ------------------------------------------------------------------------
[ dbug ] (**) STAGE :   start stage timer
[ proc ] downloading & installing 31 IPKGs ...
[ done ] downloaded & installed 31 IPKGs
[ dbug ] (**) STAGE :        elapsed time: 00h:01m:13s
[ dbug ] (II) ------------------------------------------------------------------------
[ dbug ] (<<) InstallIPKGBatch() [0]
[ dbug ] (<<) InstallIPKGs() [0]
[ dbug ] (>>) InstallPy3Modules()
[ proc ] downloading & installing 'Python 3' modules ...
[ done ] downloaded & installed 'Python 3' modules
[ dbug ] (<<) InstallPy3Modules() [0]
[ dbug ] (<<) InstallQPKGIndepsAddons() [0]
[ dbug ] (>>) InstallTargetQPKG()
[ proc ] installing QPKG (SABnzbd_200820.qpkg) - this can take a while ...
[ done ] installed QPKG (SABnzbd_200820.qpkg)
[ dbug ] (II) 'SABnzbd' service started OK
[ dbug ] (<<) InstallTargetQPKG() [0]
[ done ] 'SABnzbd' has been successfully installed!
[ dbug ] (II) ------------------------------------------------------------------------
[ dbug ] (**) SCRIPT:            finished: Wed Aug 19 14:53:01 PDT 2020
[ dbug ] (**) SCRIPT:        elapsed time: 00h:02m:35s
[ dbug ] (II) ========================================================================

**Comment by entrican** [comment]
as a side note, I was able to edit /etc/init.d/sabnzbd.sh to use /opt/bin/python as the DEAMON env variable and I was able to start SABnzbd.

I'm concerned this will get overwritten at some point and I would have assumed the new code would havea been set to use the requisite version of python.  I believe the re-install of "Entware" also removed 2.7 on my device, not sure if that broke anything else, but SickChill is toast at the moment, my version can't run on anything 3.x and above.

**Comment by OneCDOnly** [comment]
Your logs looks fine. 👍🏽 

The new SABnzbd3 is a new QPKG with a new service script `/etc/init.d/sabnzbd3.sh`. 

The old SABnzbdplus is SAB2 for Python 2. 

You'll need to backup the settings from your old SABnzbdplus. I recently posted how to do this here: https://github.com/sabnzbd/sabnzbd/issues/1578#issuecomment-674576552

**Comment by OneCDOnly** [comment]
BTW: I've just added a new option to SABnzbd QPKG v200820b that will manage the import process from SABnzbd 2 automatically. 

To try it out, please reinstall your SABnzbd 3:
```
./sherpa.sh sab
```
.. then run the updated service script with the `import` option:
```
/etc/init.d/sabnzbd3.sh import
```

**Comment by entrican** [comment]
that did the trick!  Thank you very much.  Is there a thread I can watch to see how the SickChill port is coming along?

**Comment by OneCDOnly** [comment]
No worries. 😄 

No, there's not really a thread, but I'm currently working on solving [this issue](https://github.com/OneCDOnly/sherpa/issues/76) as it seems to be related to how sherpa installs SickChill.

If you're using SickChill and find a problem that isn't a 'live' issue here, please create a new issue for it. 👍🏽
