### ISSUE TITLE
/dev/shm/__sherpa-main__.sh: line 179: syntax error: unexpected "(" (expecting "}")

### ISSUE THREAD

**Issue by cbachor** [OneCDOnly/sherpa#90]
Hi OneCD, 

Been a long time user of you sab installer, just did a NAS restart this evening and sab no longer starts, first tried to restart and get the error below: 

Error:
`[/share/Public] # /etc/init.d/sabnzbd.sh restart
= (SABnzbdplus) is not active
= (SABnzbdplus) is not active
* updating (SABnzbdplus): OK
* updating language support (SABnzbdplus): Traceback (most recent call last):
  File "tools/make_mo.py", line 295, in <module>
    make_templates()
  File "tools/make_mo.py", line 217, in make_templates
    translate_tmpl("email", lng)
  File "tools/make_mo.py", line 193, in translate_tmpl
    with open(EMAIL_DIR + "/%s-en.tmpl" % prefix, "r", encoding="utf-8") as src:
TypeError: 'encoding' is an invalid keyword argument for this function
failed!
result=[1]
Email MO files
Compile locale/da/LC_MESSAGES/SABemail.mo
Compile locale/de/LC_MESSAGES/SABemail.mo
Compile locale/en/LC_MESSAGES/SABemail.mo
Compile locale/es/LC_MESSAGES/SABemail.mo
Compile locale/fi/LC_MESSAGES/SABemail.mo
Compile locale/fr/LC_MESSAGES/SABemail.mo
Compile locale/he/LC_MESSAGES/SABemail.mo
Compile locale/nb/LC_MESSAGES/SABemail.mo
Compile locale/nl/LC_MESSAGES/SABemail.mo
Compile locale/pl/LC_MESSAGES/SABemail.mo
Compile locale/pt_BR/LC_MESSAGES/SABemail.mo
Compile locale/ro/LC_MESSAGES/SABemail.mo
Compile locale/ru/LC_MESSAGES/SABemail.mo
Compile locale/sr/LC_MESSAGES/SABemail.mo
Compile locale/sv/LC_MESSAGES/SABemail.mo
Compile locale/zh_CN/LC_MESSAGES/SABemail.mo
Create email templates from MO files
Create email template for da
* updating (nzbToMedia): OK
* starting (SABnzbdplus): failed!
result=[1]
Sorry, requires Python 3.5 or above
You can read more at: https://sabnzbd.org/python3`

When i go to reinstall the package, I run these commands, and then get the following error:
`[/share/Public] # curl -skLO https://git.io/sherpa.sh && chmod +x sherpa.sh
[/share/Public] # ./sherpa.sh SABnzbd
/dev/shm/__sherpa-main__.sh: line 179: syntax error: unexpected "(" (expecting "}")`

Please let me know what other info I can provide

**Comment by OneCDOnly** [comment]
Hi, and thanks for posting your log. 👍🏽 

I've just pushed a new `sherpa.sh` that will execute the `__sherpa-main__.sh` as a BASH script instead of SH. Can you please download it and try it out?

**Comment by OneCDOnly** [comment]
Also, if you're migrating from the old SABnzbdplus package, I included an option in the new package service script to import your configuration from your old SABnzbdplus installation. 

When you've got the new SABnzbd3 package installed, run this:
```
/etc/init/sabnzbd3.sh import
```

**Comment by cbachor** [comment]
ok checking now...

**Comment by cbachor** [comment]
making progress, installer works, now failing on start: 

`[/share/Public] # ./sherpa.sh SABnzbd
sherpa.sh (200820f)

[ done ] downloaded QPKG (SABnzbd_200820b.qpkg)            
[ done ] 'Entware' package list is up-to-date              
[ done ] no IPKGs are required                
[ done ] downloaded & installed 'Python 3' modules             
[ done ] installed QPKG (SABnzbd_200820b.qpkg)                                    
[ done ] 'SABnzbd' has been successfully reinstalled!                             

[/share/Public] # cd /etc/init.d
[/etc/init.d] # ./sabnzbd.sh 
Usage: ./sabnzbd.sh {start|stop|restart}
[/etc/init.d] # ./sabnzbd.sh restart
= (SABnzbdplus) is not active
= (SABnzbdplus) is not active
* updating (SABnzbdplus): OK
* updating (nzbToMedia): OK
* starting (SABnzbdplus): failed!
result=[127]
./sabnzbd.sh: line 167: /opt/bin/python2.7: No such file or directory
[/etc/init.d] # 
`

**Comment by OneCDOnly** [comment]
That's OK, that's the old service script we're seeing. You should now be good to run the new one with the `import` option.

**Comment by cbachor** [comment]
you're awesome ! testing things out now... do i need to remove the old version / files?

`[/etc/init.d] # ./sabnzbd3.sh import
= (SABnzbdplus) is not active
* updating SABnzbd2 configuration backup for SABnzbd3: OK
= daemon is running
* checking for UI port 8900 response: (waiting for up to 60 seconds): OK
= 'SABnzbd' UI is listening on HTTP port 8900
* stopping daemon with SIGTERM: (waiting for up to 60 seconds): 1, OK
* restoring configuration backup: OK
= daemon is not running
* updating 'SABnzbd' from remote repository: OK
* starting daemon: OK
* checking for UI port 8800 response: (waiting for up to 60 seconds): 1, 2, 3, 4, 5, 6, OK
= 'SABnzbd' UI is listening on HTTP port 8800
`

**Comment by OneCDOnly** [comment]
Good work! 😄 

Yes, once you're satisfied the new version has imported your settings, you can then uninstall the old SABnzbdplus QPKG via your App Center.

**Comment by cbachor** [comment]
very cool - can't tell you how much I use this - please let me know if there is somewhere I can donate to your efforts.

**Comment by OneCDOnly** [comment]
Awesome! 

No need for a donation, but I do appreciate your willingness to make this project better. 😄
