### ISSUE TITLE
SABnzbd: trying to update sab to 3.0.1

### ISSUE THREAD

**Issue by chutechie** [OneCDOnly/sherpa#93]
Failing at installing python 3 it looks like. 
Logs:
https://l.termbin.com/euyr

[/share/Public] # ./sherpa.sh sab
sherpa.sh (200821)

[ done ] 'Entware' package list is up-to-date
[ done ] no IPKGs are required
[ fail ] Download & install 'Python 3' modules failed ! result: [1]
[ fail ] 'SABnzbd' reinstall failed! [0]

**Comment by chutechie** [comment]
https://l.termbin.com/b6g3

I tried it on friday and wasn't sure if it completed or not. I left the computer and when I came back it was off/timed out i guess. 
I ran it again today and got failed on python. 

https://l.termbin.com/b6g3

**Comment by OneCDOnly** [comment]
OK, [recently](https://forum.qnap.com/viewtopic.php?p=762654#p762654) @TheMask had this same error, and we have only been able to track it back to the Python 3.7.4 downgrade that occurs when the `OWatcher3` QPKG is installed. 

The solution was to `stop` the `OWatcher3` QPKG in your App Center, then reinstall Entware so all the Python packages are updated to 3.8.3. 
```
./sherpa.sh ew
```
That should prevent the error occurring. This means you won't be able to use OWatcher3, so instead I suggest switching to the [Watcher3 QPKG](https://qnapclub.eu/en/qpkg/471) available in the Qnapclub repo. This is a standalone package with its own compatible Python interpreter.

**Comment by chutechie** [comment]
That did it thanks so much!!
